import { Buffer } from "node:buffer";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { InstallError } from "./errors.js";

/**
 * Codex reads instructions from AGENTS.md rather than a rules directory,
 * so the codex target syncs rules into a managed, marker-fenced block:
 *
 *   <!-- skillfold:rules:start -->
 *   <!-- Generated by skillfold ... -->
 *   <!-- skillfold:rule:code-style -->
 *   ...rule content...
 *   <!-- skillfold:rules:end -->
 *
 * Everything outside the markers is hand-authored and never touched. Rule
 * contents round-trip byte-exact (each section is the rule file verbatim
 * plus one separator newline), so `check` can verify the block offline
 * against the lockfile's content hashes.
 */

export const RULES_BLOCK_START = "<!-- skillfold:rules:start -->";
export const RULES_BLOCK_END = "<!-- skillfold:rules:end -->";
const RULES_BLOCK_NOTE =
  '<!-- Generated by skillfold from skillfold.yaml. Do not edit between the markers; edit the manifest and run "skillfold install". -->';
const RULE_MARKER_RE = /^<!-- skillfold:rule:([a-z0-9](?:[a-z0-9-]*[a-z0-9])?) -->$/gm;

export interface RuleContent {
  name: string;
  content: Buffer;
}

function ruleMarker(name: string): string {
  return `<!-- skillfold:rule:${name} -->`;
}

/** Any skillfold marker on its own line, anywhere in a rule's content. */
const EMBEDDED_MARKER_RE = /^<!-- skillfold:(rules:start|rules:end|rule:[^ ]+) -->\r?$/m;

/**
 * Reject content the block format cannot carry: marker-shaped lines would
 * corrupt parsing, and non-UTF-8 bytes would not survive the text round-trip.
 */
function validateRuleContent(rule: RuleContent): string {
  const text = rule.content.toString("utf-8");
  if (!Buffer.from(text, "utf-8").equals(rule.content)) {
    throw new InstallError(
      `rule "${rule.name}" is not valid UTF-8 text; the AGENTS.md rules block only carries text rules`
    );
  }
  const marker = EMBEDDED_MARKER_RE.exec(text);
  if (marker) {
    throw new InstallError(
      `rule "${rule.name}" contains a skillfold marker line (${marker[0].trim()}); ` +
        `remove it, it would corrupt the AGENTS.md rules block`
    );
  }
  return text;
}

/** The full managed block for a set of rules (no surrounding blank lines). */
export function buildRulesBlock(rules: RuleContent[]): string {
  let out = `${RULES_BLOCK_START}\n${RULES_BLOCK_NOTE}\n`;
  for (const rule of rules) {
    out += `${ruleMarker(rule.name)}\n${validateRuleContent(rule)}\n`;
  }
  return out + RULES_BLOCK_END;
}

/**
 * Parse the managed block out of an AGENTS.md. Returns null when the file
 * has no block. Throws InstallError on unpaired markers.
 */
export function extractRulesBlock(content: string, path: string): RuleContent[] | null {
  const start = content.indexOf(RULES_BLOCK_START);
  const end = content.indexOf(RULES_BLOCK_END);
  if (start === -1 && end === -1) return null;
  if (start === -1 || end === -1 || end < start) {
    throw new InstallError(
      `${path}: unpaired skillfold rules markers; restore both markers or remove the block`
    );
  }
  const body = content.slice(start + RULES_BLOCK_START.length, end);
  const rules: RuleContent[] = [];
  const markers: { name: string; index: number; length: number }[] = [];
  RULE_MARKER_RE.lastIndex = 0;
  for (let m = RULE_MARKER_RE.exec(body); m; m = RULE_MARKER_RE.exec(body)) {
    markers.push({ name: m[1], index: m.index, length: m[0].length });
  }
  for (let i = 0; i < markers.length; i++) {
    const from = markers[i].index + markers[i].length + 1; // skip the marker line's newline
    const to = i + 1 < markers.length ? markers[i + 1].index : body.length;
    // Drop exactly the one separator newline buildRulesBlock appends.
    const section = body.slice(from, to).replace(/\n$/, "");
    rules.push({ name: markers[i].name, content: Buffer.from(section, "utf-8") });
  }
  return rules;
}

/**
 * Insert, replace, or (with an empty rule set) remove the managed block in
 * an AGENTS.md body, leaving everything outside the markers untouched.
 * `path` is used in error messages only.
 */
export function upsertRulesBlock(
  existing: string,
  rules: RuleContent[],
  path = "AGENTS.md"
): string {
  const start = existing.indexOf(RULES_BLOCK_START);
  const end = existing.indexOf(RULES_BLOCK_END);
  const block = rules.length > 0 ? buildRulesBlock(rules) : null;
  if (start === -1 && end === -1) {
    if (!block) return existing;
    if (!existing.trim()) return `${block}\n`;
    return `${existing.replace(/\n*$/, "")}\n\n${block}\n`;
  }
  if (start === -1 || end === -1 || end < start) {
    throw new InstallError(
      `${path}: unpaired skillfold rules markers; restore both markers or remove the block`
    );
  }
  const before = existing.slice(0, start);
  const after = existing.slice(end + RULES_BLOCK_END.length);
  if (!block) {
    const merged = `${before.replace(/\n*$/, "")}\n${after.replace(/^\n*/, "")}`;
    return merged.trim() ? merged.replace(/^\n+/, "") : "";
  }
  return `${before}${block}${after}`;
}

export interface AgentsMdSyncResult {
  /** Rules newly added to or changed inside the block. */
  installed: string[];
  /** Rules whose block section was already up to date. */
  unchanged: string[];
  /** Rules removed from the block because they left the manifest. */
  pruned: string[];
}

/**
 * Sync the managed rules block in the AGENTS.md at `path`, reporting what
 * happened per rule (by diffing the previous block). Creates the file when
 * rules exist and it does not; deletes it again if removal of the block
 * leaves it empty.
 */
export function syncAgentsMd(path: string, rules: RuleContent[]): AgentsMdSyncResult {
  const result: AgentsMdSyncResult = { installed: [], unchanged: [], pruned: [] };
  const exists = existsSync(path);
  if (!exists && rules.length === 0) return result;
  const existing = exists ? readFileSync(path, "utf-8") : "";
  const previous = new Map(
    (extractRulesBlock(existing, path) ?? []).map((rule) => [rule.name, rule.content])
  );
  const current = new Set(rules.map((rule) => rule.name));
  for (const rule of rules) {
    const before = previous.get(rule.name);
    if (before && before.equals(rule.content)) result.unchanged.push(rule.name);
    else result.installed.push(rule.name);
  }
  for (const name of previous.keys()) {
    if (!current.has(name)) result.pruned.push(name);
  }
  const updated = upsertRulesBlock(existing, rules, path);
  if (updated === existing) return result;
  if (!updated.trim() && exists) {
    rmSync(path, { force: true });
    return result;
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, updated);
  return result;
}
