import { Buffer } from "node:buffer";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

import { InstallError } from "./errors.js";

/**
 * Codex reads instructions from AGENTS.md rather than a rules directory,
 * so the codex target syncs rules into a managed, marker-fenced block:
 *
 *   <!-- skillfold:rules:start -->
 *   <!-- Generated by skillfold ... -->
 *   <!-- skillfold:rule:code-style -->
 *   ...rule content...
 *   <!-- skillfold:rules:end -->
 *
 * Everything outside the markers is hand-authored and never touched. Rule
 * contents round-trip byte-exact (each section is the rule file verbatim
 * plus one separator newline), so `check` can verify the block offline
 * against the lockfile's content hashes.
 */

export const RULES_BLOCK_START = "<!-- skillfold:rules:start -->";
export const RULES_BLOCK_END = "<!-- skillfold:rules:end -->";
const RULES_BLOCK_NOTE =
  '<!-- Generated by skillfold from skillfold.yaml. Do not edit between the markers; edit the manifest and run "skillfold install". -->';
const RULE_MARKER_RE = /^<!-- skillfold:rule:([a-z0-9](?:[a-z0-9-]*[a-z0-9])?) -->$/gm;

export interface RuleContent {
  name: string;
  content: Buffer;
}

function ruleMarker(name: string): string {
  return `<!-- skillfold:rule:${name} -->`;
}

/** The full managed block for a set of rules (no surrounding blank lines). */
export function buildRulesBlock(rules: RuleContent[]): string {
  let out = `${RULES_BLOCK_START}\n${RULES_BLOCK_NOTE}\n`;
  for (const rule of rules) {
    out += `${ruleMarker(rule.name)}\n${rule.content.toString("utf-8")}\n`;
  }
  return out + RULES_BLOCK_END;
}

/**
 * Parse the managed block out of an AGENTS.md. Returns null when the file
 * has no block. Throws InstallError on unpaired markers.
 */
export function extractRulesBlock(content: string, path: string): RuleContent[] | null {
  const start = content.indexOf(RULES_BLOCK_START);
  const end = content.indexOf(RULES_BLOCK_END);
  if (start === -1 && end === -1) return null;
  if (start === -1 || end === -1 || end < start) {
    throw new InstallError(
      `${path}: unpaired skillfold rules markers; restore both markers or remove the block`
    );
  }
  const body = content.slice(start + RULES_BLOCK_START.length, end);
  const rules: RuleContent[] = [];
  const markers: { name: string; index: number; length: number }[] = [];
  RULE_MARKER_RE.lastIndex = 0;
  for (let m = RULE_MARKER_RE.exec(body); m; m = RULE_MARKER_RE.exec(body)) {
    markers.push({ name: m[1], index: m.index, length: m[0].length });
  }
  for (let i = 0; i < markers.length; i++) {
    const from = markers[i].index + markers[i].length + 1; // skip the marker line's newline
    const to = i + 1 < markers.length ? markers[i + 1].index : body.length;
    // Drop exactly the one separator newline buildRulesBlock appends.
    const section = body.slice(from, to).replace(/\n$/, "");
    rules.push({ name: markers[i].name, content: Buffer.from(section, "utf-8") });
  }
  return rules;
}

/**
 * Insert, replace, or (with an empty rule set) remove the managed block in
 * an AGENTS.md body, leaving everything outside the markers untouched.
 */
export function upsertRulesBlock(existing: string, rules: RuleContent[]): string {
  const start = existing.indexOf(RULES_BLOCK_START);
  const end = existing.indexOf(RULES_BLOCK_END);
  const block = rules.length > 0 ? buildRulesBlock(rules) : null;
  if (start === -1 && end === -1) {
    if (!block) return existing;
    if (!existing.trim()) return `${block}\n`;
    return `${existing.replace(/\n*$/, "")}\n\n${block}\n`;
  }
  if (start === -1 || end === -1 || end < start) {
    throw new InstallError(
      "AGENTS.md has unpaired skillfold rules markers; restore both markers or remove the block"
    );
  }
  const before = existing.slice(0, start);
  const after = existing.slice(end + RULES_BLOCK_END.length);
  if (!block) {
    const merged = `${before.replace(/\n*$/, "")}\n${after.replace(/^\n*/, "")}`;
    return merged.trim() ? merged.replace(/^\n+/, "") : "";
  }
  return `${before}${block}${after}`;
}

export type AgentsMdSyncStatus = "installed" | "unchanged" | "removed" | "skipped";

/**
 * Sync the managed rules block in the AGENTS.md at `path`. Creates the file
 * when rules exist and it does not; deletes it again if removal of the
 * block leaves it empty. Returns what happened.
 */
export function syncAgentsMd(path: string, rules: RuleContent[]): AgentsMdSyncStatus {
  const exists = existsSync(path);
  if (!exists && rules.length === 0) return "skipped";
  const existing = exists ? readFileSync(path, "utf-8") : "";
  let updated: string;
  try {
    updated = upsertRulesBlock(existing, rules);
  } catch (err) {
    if (err instanceof InstallError) {
      throw new InstallError(err.message.replace("AGENTS.md has", `${path} has`));
    }
    throw err;
  }
  if (updated === existing) return "unchanged";
  if (!updated.trim() && exists) {
    rmSync(path, { force: true });
    return "removed";
  }
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, updated);
  return rules.length > 0 ? "installed" : "removed";
}
