import { Buffer } from "node:buffer";

import { stringify as stringifyYaml } from "yaml";

import type { ComposeEntry } from "./manifest.js";
import type { SkillContent } from "./skill.js";

/**
 * Composition: a composed skill is a generated SKILL.md whose body is the
 * concatenation of the bodies of the skills it uses, in declared order.
 * Composed skills can use other composed skills; nesting inserts the
 * composed body, never the provenance header.
 */

export interface ComposeInput {
  description: string;
  body: string;
}

const GENERATED_NOTE =
  '<!-- Generated by skillfold from skillfold.yaml. Do not edit; edit the manifest and run "skillfold install". -->';

/** The body of a composed skill, without frontmatter or provenance comments. */
export function composeBody(parts: string[]): string {
  return parts
    .map((part) => part.trim())
    .filter(Boolean)
    .join("\n\n");
}

export function defaultComposeDescription(use: string[]): string {
  return `Composed skill combining ${use.join(", ")}.`;
}

/**
 * Generate the full SKILL.md and skill content for a composed skill.
 * `inputs` must be in the same order as `entry.use`.
 */
export function generateComposedSkill(
  name: string,
  entry: ComposeEntry,
  inputs: ComposeInput[]
): SkillContent {
  const description = entry.description || defaultComposeDescription(entry.use);
  const body = composeBody(inputs.map((input) => input.body));
  const frontmatter = stringifyYaml({ name, description }).trimEnd();
  const skillMd = [
    "---",
    frontmatter,
    "---",
    "",
    GENERATED_NOTE,
    `<!-- Composed from: ${entry.use.join(", ")} -->`,
    "",
    body,
    "",
  ].join("\n");
  return {
    name,
    description,
    body,
    files: [{ path: "SKILL.md", content: Buffer.from(skillMd, "utf-8") }],
  };
}

/**
 * Order composed skill names so that every composed dependency comes before
 * its dependents. Cycles are rejected at manifest parse time.
 */
export function composeOrder(compose: Record<string, ComposeEntry>): string[] {
  const order: string[] = [];
  const done = new Set<string>();
  const visit = (name: string): void => {
    if (done.has(name)) return;
    done.add(name);
    for (const dep of compose[name].use) {
      if (compose[dep]) visit(dep);
    }
    order.push(name);
  };
  for (const name of Object.keys(compose)) visit(name);
  return order;
}
