import assert from "node:assert/strict";
import { Buffer } from "node:buffer";
import { describe, it } from "node:test";

import {
  composeAllowedTools,
  composeBody,
  composeOrder,
  defaultComposeDescription,
  generateComposedSkill,
} from "./compose.js";
import { parseFrontmatter } from "./skill.js";

describe("composeBody", () => {
  it("joins trimmed parts with blank lines", () => {
    assert.equal(composeBody(["# A\n\n", "\n# B"]), "# A\n\n# B");
  });

  it("drops empty parts", () => {
    assert.equal(composeBody(["# A", "   ", "# B"]), "# A\n\n# B");
  });

  it("prepends a root heading and demotes inputs when a title is given", () => {
    assert.equal(
      composeBody(["# A\n\n## Approach", "# B\n\n## Approach"], "Combo"),
      "# Combo\n\n## A\n\n### Approach\n\n## B\n\n### Approach"
    );
  });

  it("normalizes inputs to the same top level regardless of their depth", () => {
    // First input starts at H1, second at H2; both top sections become H2.
    assert.equal(
      composeBody(["# A\n\n## Sub", "## B\n\n### Sub"], "Combo"),
      "# Combo\n\n## A\n\n### Sub\n\n## B\n\n### Sub"
    );
  });

  it("does not rewrite headings inside fenced code blocks", () => {
    const out = composeBody(["# A\n\n```md\n# not a heading\n```"], "Combo");
    assert.match(out, /## A/);
    assert.match(out, /```md\n# not a heading\n```/);
  });

  it("leaves headingless parts as prose under the root", () => {
    assert.equal(composeBody(["just prose"], "Combo"), "# Combo\n\njust prose");
  });
});

describe("generateComposedSkill", () => {
  const entry = { description: "Review with tests.", use: ["review", "testing"] };
  const inputs = [
    { description: "Reviews code.", body: "# Review\n\nLook closely." },
    { description: "Writes tests.", body: "# Testing\n\nTest well." },
  ];

  it("produces a single SKILL.md", () => {
    const skill = generateComposedSkill("reviewer", entry, inputs);
    assert.deepEqual(
      skill.files.map((f) => f.path),
      ["SKILL.md"]
    );
  });

  it("has valid frontmatter and provenance", () => {
    const skill = generateComposedSkill("reviewer", entry, inputs);
    const text = skill.files[0].content.toString("utf-8");
    const { attrs, body } = parseFrontmatter(text);
    assert.equal(attrs.name, "reviewer");
    assert.equal(attrs.description, "Review with tests.");
    assert.match(body, /Generated by skillfold/);
    assert.match(body, /Composed from: review, testing/);
    assert.ok(text.indexOf("## Review") < text.indexOf("## Testing"));
  });

  it("nests inputs under a single root heading named for the skill", () => {
    const skill = generateComposedSkill("reviewer", entry, inputs);
    const { body } = parseFrontmatter(skill.files[0].content.toString("utf-8"));
    // Root H1 from the skill name, each input demoted to H2.
    assert.match(body, /^# Reviewer$/m);
    assert.match(body, /^## Review$/m);
    assert.match(body, /^## Testing$/m);
    // Exactly one H1: the root. Inputs no longer bring their own top-level.
    const h1s = body.split("\n").filter((l) => /^# \S/.test(l));
    assert.equal(h1s.length, 1);
  });

  it("defaults the description", () => {
    const skill = generateComposedSkill("reviewer", { use: ["a", "b"] }, inputs);
    assert.equal(skill.description, "Composed skill combining a, b.");
  });

  it("escapes tricky descriptions in frontmatter", () => {
    const skill = generateComposedSkill(
      "tricky",
      { description: 'Has: colons, "quotes" and #hashes', use: ["a"] },
      [inputs[0]]
    );
    const { attrs } = parseFrontmatter(skill.files[0].content.toString("utf-8"));
    assert.equal(attrs.description, 'Has: colons, "quotes" and #hashes');
  });
});

describe("composeOrder", () => {
  it("puts dependencies before dependents", () => {
    const order = composeOrder({
      outer: { use: ["inner", "a"] },
      inner: { use: ["a"] },
    });
    assert.ok(order.indexOf("inner") < order.indexOf("outer"));
  });

  it("handles chains", () => {
    const order = composeOrder({
      c: { use: ["b"] },
      b: { use: ["a-skill"] },
      a: { use: ["c"] },
    });
    assert.deepEqual(order, ["b", "c", "a"]);
  });
});

describe("compose supporting files", () => {
  const file = (path: string, content: string) => ({ path, content: Buffer.from(content) });
  const input = (name: string, files: { path: string; content: Buffer }[] = []) => ({
    name,
    description: `${name} does things.`,
    body: `# ${name}`,
    files,
  });

  it("carries supporting files from the used skills", () => {
    const skill = generateComposedSkill("combo", { use: ["a", "b"] }, [
      input("a", [file("references/a.md", "A notes")]),
      input("b", [file("scripts/run.sh", "echo b")]),
    ]);
    assert.deepEqual(
      skill.files.map((f) => f.path),
      ["SKILL.md", "references/a.md", "scripts/run.sh"]
    );
  });

  it("collapses identical duplicates from a shared dependency", () => {
    const shared = file("references/shared.md", "same bytes");
    const skill = generateComposedSkill("combo", { use: ["a", "b"] }, [
      input("a", [shared]),
      input("b", [file("references/shared.md", "same bytes")]),
    ]);
    assert.deepEqual(
      skill.files.map((f) => f.path),
      ["SKILL.md", "references/shared.md"]
    );
  });

  it("errors when two skills provide the same path with different contents", () => {
    assert.throws(
      () =>
        generateComposedSkill("combo", { use: ["a", "b"] }, [
          input("a", [file("references/x.md", "from a")]),
          input("b", [file("references/x.md", "from b")]),
        ]),
      /"a" and "b" both provide "references\/x.md"/
    );
  });

  it("never inherits an input's SKILL.md", () => {
    const skill = generateComposedSkill("combo", { use: ["a"] }, [
      input("a", [file("SKILL.md", "should not leak")]),
    ]);
    assert.equal(skill.files.length, 1);
    assert.match(skill.files[0].content.toString(), /Generated by skillfold/);
  });
});

describe("compose allowed-tools", () => {
  const input = (name: string, allowedTools: string[] | undefined) => ({
    name,
    description: "d",
    body: `# ${name}`,
    allowedTools,
  });

  it("unions the inputs' tools in first-appearance order", () => {
    assert.deepEqual(
      composeAllowedTools({ use: ["a", "b"] }, [
        input("a", ["Read", "Grep"]),
        input("b", ["Grep", "Bash"]),
      ]),
      ["Read", "Grep", "Bash"]
    );
  });

  it("prefers the entry's explicit list", () => {
    assert.deepEqual(
      composeAllowedTools({ use: ["a"], allowedTools: ["Write"] }, [input("a", ["Read"])]),
      ["Write"]
    );
  });

  it("omits the union when any input is unrestricted", () => {
    assert.equal(
      composeAllowedTools({ use: ["a", "b"] }, [input("a", ["Read"]), input("b", undefined)]),
      undefined
    );
  });

  it("writes the union into the generated frontmatter", () => {
    const skill = generateComposedSkill("combo", { use: ["a", "b"] }, [
      input("a", ["Read"]),
      input("b", ["Grep"]),
    ]);
    assert.equal(skill.attrs["allowed-tools"], "Read, Grep");
  });

  it("omits the frontmatter line when no input declares tools", () => {
    const skill = generateComposedSkill("combo", { use: ["a"] }, [input("a", undefined)]);
    assert.equal(skill.attrs["allowed-tools"], undefined);
    assert.ok(!skill.files[0].content.toString().includes("allowed-tools"));
  });
});
