import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { generateAgents, generateGeminiAgents, generateRunCommand, generateTeamBootstrap } from "./agent.js";
import { type Config, isComposed } from "./config.js";
import { CompileError } from "./errors.js";
import { generateOrchestrator } from "./orchestrator.js";

export type CompileTarget = "skill" | "claude-code" | "agent-teams" | "cursor" | "windsurf" | "codex" | "copilot" | "gemini" | "goose" | "roo-code" | "kiro" | "junie";

function expand(
  name: string,
  config: Config,
  bodies: Map<string, string>,
  seen: Set<string>
): string[] {
  if (seen.has(name)) {
    throw new CompileError(name, "Circular composition during expansion");
  }

  const skill = config.skills[name];
  if (!skill) {
    throw new CompileError(name, "Unknown skill");
  }

  if (!isComposed(skill)) {
    const body = bodies.get(name);
    if (body === undefined) {
      throw new CompileError(name, "No resolved body for atomic skill");
    }
    return [body];
  }

  seen.add(name);
  const parts: string[] = [];
  for (const ref of skill.compose) {
    parts.push(...expand(ref, config, bodies, new Set(seen)));
  }
  return parts;
}

/**
 * Walk a skill's composition tree and collect the names of all atomic skills
 * it expands to (in order, with duplicates).
 */
function expandAtomicNames(
  name: string,
  config: Config,
  seen: Set<string>,
): string[] {
  if (seen.has(name)) return [];

  const skill = config.skills[name];
  if (!skill) return [];

  if (!isComposed(skill)) {
    return [name];
  }

  seen.add(name);
  const names: string[] = [];
  for (const ref of skill.compose) {
    names.push(...expandAtomicNames(ref, config, new Set(seen)));
  }
  return names;
}

export interface CompileStats {
  agents: number;
  skills: number;
  shared: number;
  linesDeduplicated: number;
}

export function computeStats(
  config: Config,
  bodies: Map<string, string>,
): CompileStats {
  const composedEntries = Object.entries(config.skills).filter(
    ([, skill]) => isComposed(skill),
  );

  // For each composed skill (agent), find which atomic skills it uses
  const agentAtomics = new Map<string, Set<string>>();
  for (const [name] of composedEntries) {
    const atomicNames = expandAtomicNames(name, config, new Set());
    agentAtomics.set(name, new Set(atomicNames));
  }

  // Collect all unique atomic skills and count how many agents use each
  const usageCount = new Map<string, number>();
  for (const atomics of agentAtomics.values()) {
    for (const atomic of atomics) {
      usageCount.set(atomic, (usageCount.get(atomic) ?? 0) + 1);
    }
  }

  const agents = composedEntries.length;
  const skills = usageCount.size;
  const shared = [...usageCount.values()].filter((count) => count >= 2).length;

  // Lines deduplicated: for each atomic skill used by N agents,
  // (N - 1) * lineCount of that skill's body
  let linesDeduplicated = 0;
  for (const [atomic, count] of usageCount) {
    if (count <= 1) continue;
    const body = bodies.get(atomic);
    if (body === undefined) continue;
    const lineCount = body.split("\n").length;
    linesDeduplicated += (count - 1) * lineCount;
  }

  return { agents, skills, shared, linesDeduplicated };
}

function formatFrontmatter(name: string, description: string): string {
  return `---\nname: ${name}\ndescription: ${description}\n---\n`;
}

function formatProvenance(configName: string, version: string, configFile: string): string {
  return `<!-- Generated by skillfold v${version} from ${configName} (${configFile}). Do not edit directly. -->\n`;
}

export interface GenerateResult {
  name: string;
  path: string;
  content: string;
}

export interface CompileResult {
  name: string;
  path: string;
}

export interface CheckResult {
  name: string;
  path: string;
  status: "ok" | "stale" | "missing";
}

export function generate(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string
): GenerateResult[] {
  const results: GenerateResult[] = [];

  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;

    const parts = expand(name, config, bodies, new Set());
    const body = parts.join("\n\n");
    const outPath = join(outDir, name, "SKILL.md");

    const output = formatFrontmatter(name, skill.description) + "\n" + body + "\n";
    results.push({ name, path: outPath, content: output });
  }

  if (config.team) {
    const orchestratorMd = generateOrchestrator(config);

    if (config.team.orchestrator) {
      const target = results.find((r) => r.name === config.team!.orchestrator);
      if (target) {
        target.content = target.content + "\n" + orchestratorMd;
      }
    } else {
      const outPath = join(outDir, "orchestrator", "SKILL.md");
      results.push({ name: "orchestrator", path: outPath, content: orchestratorMd });
    }
  }

  const provenance = formatProvenance(config.name, version, configFile);
  for (const result of results) {
    result.content = provenance + result.content;
  }

  return results;
}

/**
 * Build a map of composed skill name -> expanded body text.
 * Used by agent generation to include composed skill content.
 */
export function expandComposedBodies(
  config: Config,
  bodies: Map<string, string>,
): Map<string, string> {
  const composedBodies = new Map<string, string>();
  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;
    const parts = expand(name, config, bodies, new Set());
    composedBodies.set(name, parts.join("\n\n"));
  }
  return composedBodies;
}

/**
 * Generate output for claude-code target: skills in skills/ subdirectory
 * and agent markdown files in agents/ subdirectory.
 */
export function generateClaudeCode(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const results: GenerateResult[] = [];

  // Generate skills under skills/ subdirectory
  const skillResults = generate(config, bodies, outDir, version, configFile);
  for (const result of skillResults) {
    // Rewrite paths: {outDir}/{name}/SKILL.md -> {outDir}/skills/{name}/SKILL.md
    result.path = join(outDir, "skills", result.name, "SKILL.md");
    results.push(result);
  }

  // Generate agent markdown files
  const composedBodies = expandComposedBodies(config, bodies);
  const agentResults = generateAgents(
    config,
    composedBodies,
    outDir,
    version,
    configFile,
    "claude-code",
  );
  for (const agent of agentResults) {
    results.push(agent);
  }

  // Generate run-pipeline command if team flow exists
  const runCommand = generateRunCommand(config, version, configFile);
  if (runCommand) {
    runCommand.path = join(outDir, "commands", "run-pipeline.md");
    results.push(runCommand);
  }

  return results;
}

/**
 * Generate output for agent-teams target: same as claude-code but with
 * a team bootstrap prompt instead of a run-pipeline command.
 */
export function generateAgentTeams(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const results: GenerateResult[] = [];

  // Generate skills under skills/ subdirectory (same as claude-code)
  const skillResults = generate(config, bodies, outDir, version, configFile);
  for (const result of skillResults) {
    result.path = join(outDir, "skills", result.name, "SKILL.md");
    results.push(result);
  }

  // Generate agent markdown files (same as claude-code)
  const composedBodies = expandComposedBodies(config, bodies);
  const agentResults = generateAgents(
    config,
    composedBodies,
    outDir,
    version,
    configFile,
    "claude-code",
  );
  for (const agent of agentResults) {
    results.push(agent);
  }

  // Generate team bootstrap prompt instead of run-pipeline command
  const bootstrap = generateTeamBootstrap(config, version, configFile);
  if (bootstrap) {
    bootstrap.path = join(outDir, "commands", "start-team.md");
    results.push(bootstrap);
  }

  return results;
}

/**
 * Generate output for cursor target: .cursor/rules/*.mdc files.
 */
export function generateCursor(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const results: GenerateResult[] = [];
  const composedBodies = expandComposedBodies(config, bodies);
  const provenance = formatProvenance(config.name, version, configFile);

  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;

    let body = composedBodies.get(name) ?? "";

    // Append orchestrator plan if this is the orchestrator
    if (config.team && name === config.team.orchestrator) {
      const orchestratorPlan = generateOrchestrator(config, true);
      body = body ? body + "\n\n" + orchestratorPlan : orchestratorPlan;
    }

    const frontmatter = [
      "---",
      `description: "${skill.description}"`,
      "alwaysApply: true",
      "---",
    ].join("\n");

    const content = provenance + frontmatter + "\n\n" + body + "\n";
    results.push({
      name,
      path: join(outDir, "rules", `${name}.mdc`),
      content,
    });
  }

  // If team exists but no orchestrator skill, generate standalone orchestrator rule
  if (config.team && !config.team.orchestrator) {
    const orchestratorMd = generateOrchestrator(config);
    const frontmatter = [
      "---",
      `description: "Pipeline orchestrator for ${config.name}"`,
      "alwaysApply: true",
      "---",
    ].join("\n");

    const content = provenance + frontmatter + "\n\n" + orchestratorMd + "\n";
    results.push({
      name: "orchestrator",
      path: join(outDir, "rules", "orchestrator.mdc"),
      content,
    });
  }

  return results;
}

/**
 * Generate output for windsurf target: .windsurf/rules/*.md files.
 */
export function generateWindsurf(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const results: GenerateResult[] = [];
  const composedBodies = expandComposedBodies(config, bodies);
  const provenance = formatProvenance(config.name, version, configFile);

  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;

    let body = composedBodies.get(name) ?? "";

    if (config.team && name === config.team.orchestrator) {
      const orchestratorPlan = generateOrchestrator(config, true);
      body = body ? body + "\n\n" + orchestratorPlan : orchestratorPlan;
    }

    const frontmatter = [
      "---",
      "trigger: always_on",
      `description: "${skill.description}"`,
      "---",
    ].join("\n");

    const content = provenance + frontmatter + "\n\n" + body + "\n";
    results.push({
      name,
      path: join(outDir, "rules", `${name}.md`),
      content,
    });
  }

  if (config.team && !config.team.orchestrator) {
    const orchestratorMd = generateOrchestrator(config);
    const frontmatter = [
      "---",
      "trigger: always_on",
      `description: "Pipeline orchestrator for ${config.name}"`,
      "---",
    ].join("\n");

    const content = provenance + frontmatter + "\n\n" + orchestratorMd + "\n";
    results.push({
      name: "orchestrator",
      path: join(outDir, "rules", "orchestrator.md"),
      content,
    });
  }

  return results;
}

/**
 * Generate output for codex target: single AGENTS.md file.
 */
export function generateCodex(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const composedBodies = expandComposedBodies(config, bodies);
  const provenance = formatProvenance(config.name, version, configFile);
  const sections: string[] = [];

  sections.push(`# ${config.name}`);

  // If team flow exists, add orchestrator plan first
  if (config.team) {
    const orchestratorMd = generateOrchestrator(config, true);
    sections.push("");
    sections.push(orchestratorMd);
  }

  // Add each composed skill as a section
  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;
    if (config.team && name === config.team.orchestrator) continue; // already included above

    const body = composedBodies.get(name) ?? "";
    sections.push("");
    sections.push(`## ${name}`);
    sections.push("");
    sections.push(`${skill.description}`);
    if (body) {
      sections.push("");
      sections.push(body);
    }
  }

  const content = provenance + sections.join("\n") + "\n";

  return [{
    name: "AGENTS",
    path: join(outDir, "AGENTS.md"),
    content,
  }];
}

/**
 * Generate output for copilot target: copilot-instructions.md and per-agent instruction files.
 */
export function generateCopilot(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const results: GenerateResult[] = [];
  const composedBodies = expandComposedBodies(config, bodies);
  const provenance = formatProvenance(config.name, version, configFile);

  // Generate root copilot-instructions.md
  const rootSections: string[] = [];
  rootSections.push(`# ${config.name}`);

  if (config.team) {
    const orchestratorMd = generateOrchestrator(config, true);
    rootSections.push("");
    rootSections.push(orchestratorMd);
  } else {
    // No team - combine all agent descriptions
    for (const [name, skill] of Object.entries(config.skills)) {
      if (!isComposed(skill)) continue;
      rootSections.push("");
      rootSections.push(`## ${name}`);
      rootSections.push("");
      rootSections.push(skill.description);
    }
  }

  results.push({
    name: "copilot-instructions",
    path: join(outDir, "copilot-instructions.md"),
    content: provenance + rootSections.join("\n") + "\n",
  });

  // Generate per-agent instruction files
  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;

    let body = composedBodies.get(name) ?? "";

    if (config.team && name === config.team.orchestrator) {
      const orchestratorPlan = generateOrchestrator(config, true);
      body = body ? body + "\n\n" + orchestratorPlan : orchestratorPlan;
    }

    const frontmatter = [
      "---",
      `applyTo: "**/*"`,
      `description: "${skill.description}"`,
      "---",
    ].join("\n");

    const content = provenance + frontmatter + "\n\n" + body + "\n";
    results.push({
      name,
      path: join(outDir, "instructions", `${name}.instructions.md`),
      content,
    });
  }

  return results;
}

/**
 * Generate output for gemini target: .gemini/agents/*.md and .gemini/skills/{name}/SKILL.md.
 */
export function generateGemini(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const results: GenerateResult[] = [];
  const provenance = formatProvenance(config.name, version, configFile);

  // Generate skills under skills/ subdirectory (name + description only)
  const skillResults = generate(config, bodies, outDir, version, configFile);
  for (const result of skillResults) {
    result.path = join(outDir, "skills", result.name, "SKILL.md");
    results.push(result);
  }

  // Generate Gemini agent markdown files
  const composedBodies = expandComposedBodies(config, bodies);
  const agentResults = generateGeminiAgents(
    config,
    composedBodies,
    outDir,
    version,
    configFile,
  );
  for (const agent of agentResults) {
    results.push(agent);
  }

  return results;
}

/**
 * Generate output for goose target: .goose/skills/{name}/SKILL.md files.
 */
export function generateGoose(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const results: GenerateResult[] = [];
  const provenance = formatProvenance(config.name, version, configFile);

  // Generate skills under skills/ subdirectory
  const skillResults = generate(config, bodies, outDir, version, configFile);
  for (const result of skillResults) {
    result.path = join(outDir, "skills", result.name, "SKILL.md");
    results.push(result);
  }

  return results;
}

/**
 * Generate output for roo-code target: .roo/skills/, .roo/rules/, and .roomodes.
 */
export function generateRooCode(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const results: GenerateResult[] = [];
  const composedBodies = expandComposedBodies(config, bodies);
  const provenance = formatProvenance(config.name, version, configFile);

  // Generate skills under skills/ subdirectory
  const skillResults = generate(config, bodies, outDir, version, configFile);
  for (const result of skillResults) {
    result.path = join(outDir, "skills", result.name, "SKILL.md");
    results.push(result);
  }

  // Generate rules files (always-on instructions per agent)
  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;

    let body = composedBodies.get(name) ?? "";

    if (config.team && name === config.team.orchestrator) {
      const orchestratorPlan = generateOrchestrator(config, true);
      body = body ? body + "\n\n" + orchestratorPlan : orchestratorPlan;
    }

    const content = provenance + body + "\n";
    results.push({
      name: `rule-${name}`,
      path: join(outDir, "rules", `${name}.md`),
      content,
    });
  }

  // Generate standalone orchestrator rule if no orchestrator skill
  if (config.team && !config.team.orchestrator) {
    const orchestratorMd = generateOrchestrator(config);
    const content = provenance + orchestratorMd + "\n";
    results.push({
      name: "rule-orchestrator",
      path: join(outDir, "rules", "orchestrator.md"),
      content,
    });
  }

  // Generate .roomodes file mapping composed skills to custom modes
  const customModes = Object.entries(config.skills)
    .filter(([, skill]) => isComposed(skill))
    .map(([name, skill]) => {
      const composed = skill as { compose: string[]; description: string };
      return {
        slug: name,
        name: name.charAt(0).toUpperCase() + name.slice(1),
        roleDefinition: composed.description,
        whenToUse: composed.description,
        groups: ["read", "edit", "command", "mcp"],
      };
    });

  const roomodesContent = provenance + JSON.stringify({ customModes }, null, 2) + "\n";
  // .roomodes goes to the parent of outDir (project root), since outDir is .roo
  results.push({
    name: "roomodes",
    path: join(dirname(outDir), ".roomodes"),
    content: roomodesContent,
  });

  return results;
}

/**
 * Generate output for kiro target: .kiro/skills/ and .kiro/steering/.
 */
export function generateKiro(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const results: GenerateResult[] = [];
  const composedBodies = expandComposedBodies(config, bodies);
  const provenance = formatProvenance(config.name, version, configFile);

  // Generate skills under skills/ subdirectory
  const skillResults = generate(config, bodies, outDir, version, configFile);
  for (const result of skillResults) {
    result.path = join(outDir, "skills", result.name, "SKILL.md");
    results.push(result);
  }

  // Generate steering files (agent instructions with frontmatter)
  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;

    let body = composedBodies.get(name) ?? "";

    if (config.team && name === config.team.orchestrator) {
      const orchestratorPlan = generateOrchestrator(config, true);
      body = body ? body + "\n\n" + orchestratorPlan : orchestratorPlan;
    }

    const frontmatter = [
      "---",
      "inclusion: always",
      "---",
    ].join("\n");

    const content = provenance + frontmatter + "\n\n" + body + "\n";
    results.push({
      name: `steering-${name}`,
      path: join(outDir, "steering", `${name}.md`),
      content,
    });
  }

  // Generate standalone orchestrator steering if no orchestrator skill
  if (config.team && !config.team.orchestrator) {
    const orchestratorMd = generateOrchestrator(config);
    const frontmatter = [
      "---",
      "inclusion: always",
      "---",
    ].join("\n");

    const content = provenance + frontmatter + "\n\n" + orchestratorMd + "\n";
    results.push({
      name: "steering-orchestrator",
      path: join(outDir, "steering", "orchestrator.md"),
      content,
    });
  }

  return results;
}

/**
 * Generate output for junie target: .junie/skills/ and .junie/guidelines.
 */
export function generateJunie(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const results: GenerateResult[] = [];
  const composedBodies = expandComposedBodies(config, bodies);
  const provenance = formatProvenance(config.name, version, configFile);

  // Generate skills under skills/ subdirectory
  const skillResults = generate(config, bodies, outDir, version, configFile);
  for (const result of skillResults) {
    result.path = join(outDir, "skills", result.name, "SKILL.md");
    results.push(result);
  }

  // Generate guideline files per agent (plain markdown, no frontmatter)
  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;

    let body = composedBodies.get(name) ?? "";

    if (config.team && name === config.team.orchestrator) {
      const orchestratorPlan = generateOrchestrator(config, true);
      body = body ? body + "\n\n" + orchestratorPlan : orchestratorPlan;
    }

    const content = provenance + body + "\n";
    results.push({
      name: `guideline-${name}`,
      path: join(outDir, `${name}_guidelines.md`),
      content,
    });
  }

  // Generate standalone orchestrator guideline if no orchestrator skill
  if (config.team && !config.team.orchestrator) {
    const orchestratorMd = generateOrchestrator(config);
    const content = provenance + orchestratorMd + "\n";
    results.push({
      name: "guideline-orchestrator",
      path: join(outDir, "orchestrator_guidelines.md"),
      content,
    });
  }

  return results;
}

function writeResults(results: GenerateResult[]): void {
  for (const result of results) {
    mkdirSync(dirname(result.path), { recursive: true });
    writeFileSync(result.path, result.content, "utf-8");
  }
}

export function compile(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
  target: CompileTarget = "skill",
): CompileResult[] {
  mkdirSync(outDir, { recursive: true });

  let generated: GenerateResult[];
  switch (target) {
    case "claude-code":
      generated = generateClaudeCode(config, bodies, outDir, version, configFile);
      break;
    case "agent-teams":
      generated = generateAgentTeams(config, bodies, outDir, version, configFile);
      break;
    case "cursor":
      generated = generateCursor(config, bodies, outDir, version, configFile);
      break;
    case "windsurf":
      generated = generateWindsurf(config, bodies, outDir, version, configFile);
      break;
    case "codex":
      generated = generateCodex(config, bodies, outDir, version, configFile);
      break;
    case "copilot":
      generated = generateCopilot(config, bodies, outDir, version, configFile);
      break;
    case "gemini":
      generated = generateGemini(config, bodies, outDir, version, configFile);
      break;
    case "goose":
      generated = generateGoose(config, bodies, outDir, version, configFile);
      break;
    case "roo-code":
      generated = generateRooCode(config, bodies, outDir, version, configFile);
      break;
    case "kiro":
      generated = generateKiro(config, bodies, outDir, version, configFile);
      break;
    case "junie":
      generated = generateJunie(config, bodies, outDir, version, configFile);
      break;
    default:
      generated = generate(config, bodies, outDir, version, configFile);
  }

  writeResults(generated);

  return generated.map(({ name, path }) => ({ name, path }));
}

export function check(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
  target: CompileTarget = "skill",
): CheckResult[] {
  let generated: GenerateResult[];
  switch (target) {
    case "claude-code":
      generated = generateClaudeCode(config, bodies, outDir, version, configFile);
      break;
    case "agent-teams":
      generated = generateAgentTeams(config, bodies, outDir, version, configFile);
      break;
    case "cursor":
      generated = generateCursor(config, bodies, outDir, version, configFile);
      break;
    case "windsurf":
      generated = generateWindsurf(config, bodies, outDir, version, configFile);
      break;
    case "codex":
      generated = generateCodex(config, bodies, outDir, version, configFile);
      break;
    case "copilot":
      generated = generateCopilot(config, bodies, outDir, version, configFile);
      break;
    case "gemini":
      generated = generateGemini(config, bodies, outDir, version, configFile);
      break;
    case "goose":
      generated = generateGoose(config, bodies, outDir, version, configFile);
      break;
    case "roo-code":
      generated = generateRooCode(config, bodies, outDir, version, configFile);
      break;
    case "kiro":
      generated = generateKiro(config, bodies, outDir, version, configFile);
      break;
    case "junie":
      generated = generateJunie(config, bodies, outDir, version, configFile);
      break;
    default:
      generated = generate(config, bodies, outDir, version, configFile);
  }
  const results: CheckResult[] = [];

  for (const result of generated) {
    if (!existsSync(result.path)) {
      results.push({ name: result.name, path: result.path, status: "missing" });
      continue;
    }

    const existing = readFileSync(result.path, "utf-8");
    if (existing === result.content) {
      results.push({ name: result.name, path: result.path, status: "ok" });
    } else {
      results.push({ name: result.name, path: result.path, status: "stale" });
    }
  }

  return results;
}
