import { afterEach, describe, it } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

import type { Config } from "./config.js";
import { CompileError } from "./errors.js";
import { check, compile, computeStats } from "./compiler.js";
import type { Graph } from "./graph.js";
import type { StateSchema } from "./state.js";

function makeTmpDir(): string {
  const dir = join(tmpdir(), `skillfold-compiler-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

describe("compile", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("single composed skill produces file with frontmatter and bodies joined by double newline", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        lint: { path: "./skills/lint" },
        format: { path: "./skills/format" },
        quality: { compose: ["lint", "format"], description: "Runs quality checks." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("lint", "Run the linter.");
    bodies.set("format", "Format the code.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.equal(results.length, 1);
    assert.equal(results[0].name, "quality");

    const content = readFileSync(results[0].path, "utf-8");
    assert.ok(content.startsWith("<!-- Generated by skillfold v0.0.0 from test (test.yaml). Do not edit directly. -->\n"));
    assert.ok(content.includes("name: quality"));
    assert.ok(content.includes("description: Runs quality checks."));
    assert.ok(content.includes("Run the linter.\n\nFormat the code.\n"));
  });

  it("recursive composition flattens to all leaf bodies in correct order", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        a: { path: "./skills/a" },
        b: { path: "./skills/b" },
        c: { path: "./skills/c" },
        inner: { compose: ["a", "b"], description: "Inner skill." },
        outer: { compose: ["inner", "c"], description: "Outer skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("a", "Body A");
    bodies.set("b", "Body B");
    bodies.set("c", "Body C");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");

    const outerResult = results.find((r) => r.name === "outer");
    assert.ok(outerResult);

    const content = readFileSync(outerResult.path, "utf-8");
    assert.ok(content.includes("Body A\n\nBody B\n\nBody C\n"));
  });

  it("output files at {skill-name}/SKILL.md", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.equal(results[0].path, join(outDir, "bundle", "SKILL.md"));
    assert.ok(existsSync(join(outDir, "bundle", "SKILL.md")));
  });

  it("atomic skills do not produce output files", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.ok(!existsSync(join(outDir, "leaf")));
  });

  it("unknown skill reference throws CompileError", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        broken: { compose: ["nonexistent"], description: "Broken skill." },
      },
    };

    const bodies = new Map<string, string>();

    assert.throws(() => compile(config, bodies, outDir, "0.0.0", "test.yaml"), (err: unknown) => {
      assert.ok(err instanceof CompileError);
      assert.match(err.message, /Unknown skill/);
      return true;
    });
  });

  it("missing body for atomic skill throws CompileError", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    // Intentionally omit body for "leaf"
    const bodies = new Map<string, string>();

    assert.throws(() => compile(config, bodies, outDir, "0.0.0", "test.yaml"), (err: unknown) => {
      assert.ok(err instanceof CompileError);
      assert.match(err.message, /No resolved body for atomic skill/);
      return true;
    });
  });

  it("config with team and orchestrator key appends orchestrator to composed skill output", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const state: StateSchema = {
      types: {},
      fields: {
        goal: { type: { kind: "primitive", value: "string" } },
      },
    };

    const graph: Graph = {
      nodes: [
        { skill: "strategy", reads: [], writes: ["state.goal"], then: "lead" },
        { skill: "lead", reads: ["state.goal"], writes: [] },
      ],
    };

    const config: Config = {
      name: "test",
      skills: {
        strategy: { path: "./skills/strategy" },
        lead: { path: "./skills/lead" },
        pipeline: { compose: ["strategy", "lead"], description: "Runs the pipeline." },
      },
      state,
      team: {
        orchestrator: "pipeline",
        flow: graph,
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("strategy", "Strategy body.");
    bodies.set("lead", "Lead body.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");

    // The pipeline/SKILL.md should exist (from composed skill output)
    const pipelineResult = results.find((r) => r.name === "pipeline");
    assert.ok(pipelineResult);
    assert.equal(pipelineResult.path, join(outDir, "pipeline", "SKILL.md"));

    const content = readFileSync(pipelineResult.path, "utf-8");
    // Should contain provenance + frontmatter
    assert.ok(content.startsWith("<!-- Generated by skillfold v0.0.0 from test (test.yaml). Do not edit directly. -->\n---\n"));
    assert.ok(content.includes("name: pipeline"));
    assert.ok(content.includes("description: Runs the pipeline."));
    // Should contain the composed bodies
    assert.ok(content.includes("Strategy body."));
    assert.ok(content.includes("Lead body."));
    // Should also contain orchestrator content
    assert.ok(content.includes("# Orchestrator: test"));
    assert.ok(content.includes("## Execution Plan"));
    assert.ok(content.includes("### Step 1: strategy"));

    // No standalone orchestrator directory should exist
    assert.ok(!existsSync(join(outDir, "orchestrator")));
  });

  it("config with team but no orchestrator key generates standalone orchestrator/SKILL.md", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: [] },
      ],
    };

    const config: Config = {
      name: "standalone-test",
      skills: {
        worker: { path: "./skills/worker" },
      },
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");

    const orchResult = results.find((r) => r.name === "orchestrator");
    assert.ok(orchResult);
    assert.equal(orchResult.path, join(outDir, "orchestrator", "SKILL.md"));

    const content = readFileSync(orchResult.path, "utf-8");
    assert.ok(content.includes("# Orchestrator: standalone-test"));
    assert.ok(content.includes("### Step 1: worker"));
  });

  it("frontmatter contains correct name and description", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        agent: { compose: ["leaf"], description: "An agent that does things." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf content.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");
    const content = readFileSync(results[0].path, "utf-8");

    // Verify provenance + frontmatter structure
    const lines = content.split("\n");
    assert.equal(lines[0], "<!-- Generated by skillfold v0.0.0 from test (test.yaml). Do not edit directly. -->");
    assert.equal(lines[1], "---");
    assert.equal(lines[2], "name: agent");
    assert.equal(lines[3], "description: An agent that does things.");
    assert.equal(lines[4], "---");
  });

  it("--target skill produces same output as default", () => {
    tmpDir = makeTmpDir();
    const outDir1 = join(tmpDir, "default");
    const outDir2 = join(tmpDir, "skill");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results1 = compile(config, bodies, outDir1, "0.0.0", "test.yaml");
    const results2 = compile(config, bodies, outDir2, "0.0.0", "test.yaml", "skill");

    assert.equal(results1.length, results2.length);
    const content1 = readFileSync(results1[0].path, "utf-8");
    const content2 = readFileSync(results2[0].path, "utf-8");
    assert.equal(content1, content2);
  });
});

describe("compile with claude-code target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs skills under skills/ subdirectory", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const skillResult = results.find((r) => r.name === "bundle" && r.path.includes("skills"));
    assert.ok(skillResult);
    assert.equal(skillResult.path, join(outDir, "skills", "bundle", "SKILL.md"));
    assert.ok(existsSync(skillResult.path));
  });

  it("outputs agent markdown files under agents/ subdirectory", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const agentResult = results.find((r) => r.path.includes("agents"));
    assert.ok(agentResult);
    assert.equal(agentResult.path, join(outDir, "agents", "bundle.md"));
    assert.ok(existsSync(agentResult.path));
  });

  it("agent files contain frontmatter and body", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const content = readFileSync(join(outDir, "agents", "bundle.md"), "utf-8");
    assert.ok(content.includes("name: bundle"));
    assert.ok(content.includes("description: A bundle skill."));
    assert.ok(content.includes("Leaf body"));
  });

  it("produces both skills and agents for config with team flow", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    // Should have skills (planner, worker, orchestrator) + agents (planner, worker)
    const skillPaths = results.filter((r) => r.path.includes("/skills/"));
    const agentPaths = results.filter((r) => r.path.includes("/agents/"));

    assert.ok(skillPaths.length >= 2);
    assert.ok(agentPaths.length >= 2);
  });

  it("generates run-pipeline command when team flow exists", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test-pipeline",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const cmdResult = results.find((r) => r.path.includes("commands"));
    assert.ok(cmdResult);
    assert.equal(cmdResult.path, join(outDir, "commands", "run-pipeline.md"));
    assert.ok(existsSync(cmdResult.path));
  });

  it("does not generate run-pipeline command when team flow is absent", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const cmdResult = results.find((r) => r.path.includes("commands"));
    assert.equal(cmdResult, undefined);
    assert.ok(!existsSync(join(outDir, "commands")));
  });

  it("run-pipeline command includes execution steps matching the flow", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: ["state.result"] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
        result: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "flow-test",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const content = readFileSync(join(outDir, "commands", "run-pipeline.md"), "utf-8");
    assert.ok(content.includes("## Execution Plan"));
    assert.ok(content.includes("### Step 1: planner"));
    assert.ok(content.includes("### Step 2: worker"));
    assert.ok(content.includes("Invoke **planner**"));
    assert.ok(content.includes("Invoke **worker**"));
  });

  it("run-pipeline command includes state table when state is defined", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
        count: { type: { kind: "primitive", value: "number" } },
      },
    };

    const config: Config = {
      name: "state-test",
      skills: {
        planning: { path: "./skills/planning" },
        planner: { compose: ["planning"], description: "Plans." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const content = readFileSync(join(outDir, "commands", "run-pipeline.md"), "utf-8");
    assert.ok(content.includes("## State"));
    assert.ok(content.includes("| plan | string |"));
    assert.ok(content.includes("| count | number |"));
  });
});

describe("check", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  function makeConfig(): { config: Config; bodies: Map<string, string> } {
    const config: Config = {
      name: "test",
      skills: {
        lint: { path: "./skills/lint" },
        format: { path: "./skills/format" },
        quality: { compose: ["lint", "format"], description: "Runs quality checks." },
      },
    };
    const bodies = new Map<string, string>();
    bodies.set("lint", "Run the linter.");
    bodies.set("format", "Format the code.");
    return { config, bodies };
  }

  it("returns ok when compiled output matches on disk", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");
    const { config, bodies } = makeConfig();

    compile(config, bodies, outDir, "0.0.0", "test.yaml");
    const results = check(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.equal(results.length, 1);
    assert.equal(results[0].name, "quality");
    assert.equal(results[0].status, "ok");
  });

  it("returns stale when on-disk content differs", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");
    const { config, bodies } = makeConfig();

    compile(config, bodies, outDir, "0.0.0", "test.yaml");
    writeFileSync(join(outDir, "quality", "SKILL.md"), "old content", "utf-8");
    const results = check(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.equal(results.length, 1);
    assert.equal(results[0].status, "stale");
  });

  it("returns missing when output file does not exist", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");
    const { config, bodies } = makeConfig();

    const results = check(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.equal(results.length, 1);
    assert.equal(results[0].status, "missing");
  });

  it("checks orchestrator output when team is defined", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: [] },
      ],
    };

    const config: Config = {
      name: "orch-test",
      skills: {
        worker: { path: "./skills/worker" },
      },
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();

    compile(config, bodies, outDir, "0.0.0", "test.yaml");
    const results = check(config, bodies, outDir, "0.0.0", "test.yaml");

    const orchResult = results.find((r) => r.name === "orchestrator");
    assert.ok(orchResult);
    assert.equal(orchResult.status, "ok");
  });
});

describe("compile with cursor target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs .mdc files under rules/ subdirectory", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "cursor");

    assert.equal(results.length, 1);
    assert.equal(results[0].name, "bundle");
    assert.equal(results[0].path, join(outDir, "rules", "bundle.mdc"));
    assert.ok(existsSync(results[0].path));
  });

  it("includes cursor frontmatter with description and alwaysApply", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "cursor");

    const content = readFileSync(join(outDir, "rules", "bundle.mdc"), "utf-8");
    assert.ok(content.includes("<!-- Generated by skillfold v0.0.0"));
    assert.ok(content.includes('description: "A bundle skill."'));
    assert.ok(content.includes("alwaysApply: true"));
    assert.ok(content.includes("Leaf body"));
  });

  it("generates standalone orchestrator rule when team has no orchestrator key", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: [] },
      ],
    };

    const config: Config = {
      name: "cursor-test",
      skills: {
        worker: { path: "./skills/worker" },
      },
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "cursor");

    const orchResult = results.find((r) => r.name === "orchestrator");
    assert.ok(orchResult);
    assert.equal(orchResult.path, join(outDir, "rules", "orchestrator.mdc"));

    const content = readFileSync(orchResult.path, "utf-8");
    assert.ok(content.includes("# Orchestrator: cursor-test"));
  });

  it("appends orchestrator plan to composed skill when orchestrator key is set", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { orchestrator: "planner", flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "cursor");

    const content = readFileSync(join(outDir, "rules", "planner.mdc"), "utf-8");
    assert.ok(content.includes("Planning body."));
    assert.ok(content.includes("# Orchestrator: test"));
    assert.ok(content.includes("## Execution Plan"));
  });
});

describe("compile with windsurf target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs .md files under rules/ subdirectory", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "windsurf");

    assert.equal(results.length, 1);
    assert.equal(results[0].name, "bundle");
    assert.equal(results[0].path, join(outDir, "rules", "bundle.md"));
    assert.ok(existsSync(results[0].path));
  });

  it("includes windsurf frontmatter with trigger and description", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "windsurf");

    const content = readFileSync(join(outDir, "rules", "bundle.md"), "utf-8");
    assert.ok(content.includes("<!-- Generated by skillfold v0.0.0"));
    assert.ok(content.includes("trigger: always_on"));
    assert.ok(content.includes('description: "A bundle skill."'));
    assert.ok(content.includes("Leaf body"));
  });

  it("generates standalone orchestrator rule when team has no orchestrator key", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: [] },
      ],
    };

    const config: Config = {
      name: "windsurf-test",
      skills: {
        worker: { path: "./skills/worker" },
      },
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "windsurf");

    const orchResult = results.find((r) => r.name === "orchestrator");
    assert.ok(orchResult);
    assert.equal(orchResult.path, join(outDir, "rules", "orchestrator.md"));

    const content = readFileSync(orchResult.path, "utf-8");
    assert.ok(content.includes("# Orchestrator: windsurf-test"));
    assert.ok(content.includes("trigger: always_on"));
  });

  it("appends orchestrator plan to composed skill when orchestrator key is set", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { orchestrator: "planner", flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "windsurf");

    const content = readFileSync(join(outDir, "rules", "planner.md"), "utf-8");
    assert.ok(content.includes("Planning body."));
    assert.ok(content.includes("# Orchestrator: test"));
  });
});

describe("compile with codex target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs single AGENTS.md file", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "codex");

    assert.equal(results.length, 1);
    assert.equal(results[0].name, "AGENTS");
    assert.equal(results[0].path, join(outDir, "AGENTS.md"));
    assert.ok(existsSync(results[0].path));
  });

  it("includes pipeline name heading and agent sections without frontmatter", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        other: { path: "./skills/other" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
        helper: { compose: ["other"], description: "A helper skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");
    bodies.set("other", "Other body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "codex");

    const content = readFileSync(join(outDir, "AGENTS.md"), "utf-8");
    assert.ok(content.includes("<!-- Generated by skillfold v0.0.0"));
    assert.ok(content.includes("# test"));
    assert.ok(content.includes("## bundle"));
    assert.ok(content.includes("A bundle skill."));
    assert.ok(content.includes("Leaf body"));
    assert.ok(content.includes("## helper"));
    assert.ok(content.includes("A helper skill."));
    assert.ok(content.includes("Other body"));
    // No YAML frontmatter delimiters
    assert.ok(!content.includes("---"));
  });

  it("includes orchestrator plan when team flow exists", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: [] },
      ],
    };

    const config: Config = {
      name: "codex-test",
      skills: {
        working: { path: "./skills/working" },
        worker: { compose: ["working"], description: "Works." },
      },
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("working", "Working body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "codex");

    const content = readFileSync(join(outDir, "AGENTS.md"), "utf-8");
    assert.ok(content.includes("# Orchestrator: codex-test"));
    assert.ok(content.includes("## Execution Plan"));
    assert.ok(content.includes("### Step 1: worker"));
  });

  it("skips orchestrator skill from agent sections when orchestrator key is set", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { orchestrator: "planner", flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "codex");

    const content = readFileSync(join(outDir, "AGENTS.md"), "utf-8");
    // Orchestrator plan is included at the top level
    assert.ok(content.includes("# Orchestrator: test"));
    // The planner section is not duplicated as a separate agent section
    assert.ok(!content.includes("## planner"));
    // The worker section is present
    assert.ok(content.includes("## worker"));
  });
});

describe("compile with copilot target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs copilot-instructions.md and per-agent instruction files", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "copilot");

    assert.equal(results.length, 2);

    const rootResult = results.find((r) => r.name === "copilot-instructions");
    assert.ok(rootResult);
    assert.equal(rootResult.path, join(outDir, "copilot-instructions.md"));
    assert.ok(existsSync(rootResult.path));

    const agentResult = results.find((r) => r.name === "bundle");
    assert.ok(agentResult);
    assert.equal(agentResult.path, join(outDir, "instructions", "bundle.instructions.md"));
    assert.ok(existsSync(agentResult.path));
  });

  it("copilot-instructions.md contains agent descriptions when no team", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "copilot");

    const content = readFileSync(join(outDir, "copilot-instructions.md"), "utf-8");
    assert.ok(content.includes("# test"));
    assert.ok(content.includes("## bundle"));
    assert.ok(content.includes("A bundle skill."));
  });

  it("per-agent files include copilot frontmatter with applyTo and description", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "copilot");

    const content = readFileSync(join(outDir, "instructions", "bundle.instructions.md"), "utf-8");
    assert.ok(content.includes("<!-- Generated by skillfold v0.0.0"));
    assert.ok(content.includes('applyTo: "**/*"'));
    assert.ok(content.includes('description: "A bundle skill."'));
    assert.ok(content.includes("Leaf body"));
  });

  it("copilot-instructions.md includes orchestrator plan when team flow exists", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "copilot");

    const content = readFileSync(join(outDir, "copilot-instructions.md"), "utf-8");
    assert.ok(content.includes("# Orchestrator: test"));
    assert.ok(content.includes("## Execution Plan"));
  });

  it("appends orchestrator plan to orchestrator agent instruction file", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { orchestrator: "planner", flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "copilot");

    const content = readFileSync(join(outDir, "instructions", "planner.instructions.md"), "utf-8");
    assert.ok(content.includes("Planning body."));
    assert.ok(content.includes("# Orchestrator: test"));
    assert.ok(content.includes("## Execution Plan"));
  });
});

describe("compile with agent-teams target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs skills under skills/ subdirectory", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "agent-teams");

    const skillResult = results.find((r) => r.name === "bundle" && r.path.includes("skills"));
    assert.ok(skillResult);
    assert.equal(skillResult.path, join(outDir, "skills", "bundle", "SKILL.md"));
    assert.ok(existsSync(skillResult.path));
  });

  it("outputs agent markdown files under agents/ subdirectory", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "agent-teams");

    const agentResult = results.find((r) => r.path.includes("agents"));
    assert.ok(agentResult);
    assert.equal(agentResult.path, join(outDir, "agents", "bundle.md"));
    assert.ok(existsSync(agentResult.path));
  });

  it("generates start-team command instead of run-pipeline when team flow exists", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test-pipeline",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans things." },
        worker: { compose: ["working"], description: "Does work." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "agent-teams");

    const cmdResult = results.find((r) => r.path.includes("commands"));
    assert.ok(cmdResult);
    assert.equal(cmdResult.path, join(outDir, "commands", "start-team.md"));
    assert.ok(existsSync(cmdResult.path));

    const content = readFileSync(cmdResult.path, "utf-8");
    assert.ok(content.includes("Create an Agent Team"));
    assert.ok(content.includes("test-pipeline"));
    assert.ok(content.includes("planner"));
    assert.ok(content.includes("worker"));
  });

  it("start-team prompt includes team structure and task sequence", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"], then: "worker" },
        { skill: "worker", reads: ["state.plan"], writes: ["state.output"] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
        output: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test-team",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Creates plans." },
        worker: { compose: ["working"], description: "Executes plans." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "agent-teams");

    const content = readFileSync(join(outDir, "commands", "start-team.md"), "utf-8");
    assert.ok(content.includes("Team Structure"));
    assert.ok(content.includes("Task Sequence"));
    assert.ok(content.includes("Creates plans."));
    assert.ok(content.includes("Executes plans."));
    assert.ok(content.includes("`state.plan`"));
    assert.ok(content.includes("`state.output`"));
    assert.ok(content.includes("Then: **worker**"));
  });

  it("start-team prompt includes conditional routing", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: ["state.result"] },
        {
          skill: "reviewer",
          reads: ["state.result"],
          writes: ["state.review"],
          then: [
            { when: "review.approved == true", to: "end" },
            { when: "review.approved == false", to: "worker" },
          ],
        },
      ],
    };

    const state: StateSchema = {
      types: {
        Review: {
          fields: {
            approved: "bool",
            feedback: "string",
          },
        },
      },
      fields: {
        result: { type: { kind: "primitive", value: "string" } },
        review: { type: { kind: "custom", name: "Review" } },
      },
    };

    const config: Config = {
      name: "review-loop",
      skills: {
        coding: { path: "./skills/coding" },
        reviewing: { path: "./skills/reviewing" },
        worker: { compose: ["coding"], description: "Writes code." },
        reviewer: { compose: ["reviewing"], description: "Reviews code." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("coding", "Code body.");
    bodies.set("reviewing", "Review body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "agent-teams");

    const content = readFileSync(join(outDir, "commands", "start-team.md"), "utf-8");
    assert.ok(content.includes("Routing:"));
    assert.ok(content.includes("review.approved == true"));
    assert.ok(content.includes("review.approved == false"));
  });

  it("does not generate start-team when no team flow", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "agent-teams");
    const cmdResult = results.find((r) => r.path.includes("commands"));
    assert.equal(cmdResult, undefined);
  });

  it("check works with agent-teams target", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "agent-teams");
    const results = check(config, bodies, outDir, "0.0.0", "test.yaml", "agent-teams");
    for (const result of results) {
      assert.equal(result.status, "ok");
    }
  });

  it("start-team prompt includes state table", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: ["state.output"] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        output: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test",
      skills: {
        working: { path: "./skills/working" },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("working", "Working body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "agent-teams");

    const content = readFileSync(join(outDir, "commands", "start-team.md"), "utf-8");
    assert.ok(content.includes("Shared State"));
    assert.ok(content.includes("| output | string |"));
  });
});

describe("compile with gemini target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs skills under skills/ subdirectory", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "gemini");

    const skillResult = results.find((r) => r.name === "bundle" && r.path.includes("skills"));
    assert.ok(skillResult);
    assert.equal(skillResult.path, join(outDir, "skills", "bundle", "SKILL.md"));
    assert.ok(existsSync(skillResult.path));
  });

  it("outputs agent markdown files under agents/ subdirectory", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "gemini");

    const agentResult = results.find((r) => r.path.includes("agents"));
    assert.ok(agentResult);
    assert.equal(agentResult.path, join(outDir, "agents", "bundle.md"));
    assert.ok(existsSync(agentResult.path));
  });

  it("agent files contain Gemini frontmatter with name and description", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "gemini");

    const content = readFileSync(join(outDir, "agents", "bundle.md"), "utf-8");
    assert.ok(content.includes("name: bundle"));
    assert.ok(content.includes("description: A bundle skill."));
    assert.ok(content.includes("Leaf body"));
    // Gemini agents should not have color field
    assert.ok(!content.includes("color:"));
  });

  it("skill files use standard Agent Skills format with name and description only", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "gemini");

    const content = readFileSync(join(outDir, "skills", "bundle", "SKILL.md"), "utf-8");
    assert.ok(content.includes("name: bundle"));
    assert.ok(content.includes("description: A bundle skill."));
    // Skills should not have model or color
    assert.ok(!content.includes("model:"));
    assert.ok(!content.includes("color:"));
  });

  it("produces both skills and agents for config with team flow", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "gemini");

    const skillPaths = results.filter((r) => r.path.includes("/skills/"));
    const agentPaths = results.filter((r) => r.path.includes("/agents/"));

    assert.ok(skillPaths.length >= 2);
    assert.ok(agentPaths.length >= 2);
  });

  it("orchestrator agent includes execution plan", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "gemini-test",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { orchestrator: "planner", flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "gemini");

    const content = readFileSync(join(outDir, "agents", "planner.md"), "utf-8");
    assert.ok(content.includes("Planning body."));
    assert.ok(content.includes("# Orchestrator: gemini-test"));
    assert.ok(content.includes("## Execution Plan"));
  });

  it("check works with gemini target", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "gemini");
    const results = check(config, bodies, outDir, "0.0.0", "test.yaml", "gemini");

    for (const result of results) {
      assert.equal(result.status, "ok");
    }
  });
});

describe("computeStats", () => {
  it("counts shared skills when 2+ agents use the same atomic skill", () => {
    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
        coding: { path: "./skills/coding" },
        review: { path: "./skills/review" },
        planner: { compose: ["planning", "coding"], description: "Plans and codes." },
        reviewer: { compose: ["coding", "review"], description: "Reviews code." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Plan line 1\nPlan line 2");
    bodies.set("coding", "Code line 1\nCode line 2\nCode line 3");
    bodies.set("review", "Review line 1");

    const stats = computeStats(config, bodies);

    assert.equal(stats.agents, 2);
    assert.equal(stats.skills, 3);
    assert.equal(stats.shared, 1); // coding is shared
    // coding has 3 lines, used by 2 agents -> (2-1)*3 = 3
    assert.equal(stats.linesDeduplicated, 3);
  });

  it("reports zero shared skills when no atomic skill appears in 2+ agents", () => {
    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
        coding: { path: "./skills/coding" },
        planner: { compose: ["planning"], description: "Plans." },
        coder: { compose: ["coding"], description: "Codes." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Plan body");
    bodies.set("coding", "Code body");

    const stats = computeStats(config, bodies);

    assert.equal(stats.agents, 2);
    assert.equal(stats.skills, 2);
    assert.equal(stats.shared, 0);
    assert.equal(stats.linesDeduplicated, 0);
  });

  it("counts line deduplication across multiple shared skills", () => {
    const config: Config = {
      name: "test",
      skills: {
        a: { path: "./skills/a" },
        b: { path: "./skills/b" },
        c: { path: "./skills/c" },
        agent1: { compose: ["a", "b", "c"], description: "Agent 1." },
        agent2: { compose: ["a", "b"], description: "Agent 2." },
        agent3: { compose: ["a", "c"], description: "Agent 3." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("a", "Line 1\nLine 2"); // 2 lines, used by 3 agents -> (3-1)*2 = 4
    bodies.set("b", "Line 1");          // 1 line, used by 2 agents -> (2-1)*1 = 1
    bodies.set("c", "Line 1\nLine 2\nLine 3"); // 3 lines, used by 2 agents -> (2-1)*3 = 3

    const stats = computeStats(config, bodies);

    assert.equal(stats.agents, 3);
    assert.equal(stats.skills, 3);
    assert.equal(stats.shared, 3); // all three are shared
    assert.equal(stats.linesDeduplicated, 8); // 4 + 1 + 3
  });

  it("handles a single agent with no sharing possible", () => {
    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
        coding: { path: "./skills/coding" },
        solo: { compose: ["planning", "coding"], description: "Solo agent." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Plan body");
    bodies.set("coding", "Code body");

    const stats = computeStats(config, bodies);

    assert.equal(stats.agents, 1);
    assert.equal(stats.skills, 2);
    assert.equal(stats.shared, 0);
    assert.equal(stats.linesDeduplicated, 0);
  });

  it("handles recursive composition when counting atomic skills", () => {
    const config: Config = {
      name: "test",
      skills: {
        a: { path: "./skills/a" },
        b: { path: "./skills/b" },
        inner: { compose: ["a", "b"], description: "Inner." },
        agent1: { compose: ["inner"], description: "Uses inner." },
        agent2: { compose: ["a"], description: "Uses a directly." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("a", "A line 1\nA line 2");
    bodies.set("b", "B line 1");

    const stats = computeStats(config, bodies);

    // agent1 uses a, b (via inner); agent2 uses a
    // inner is also composed but not a top-level agent output... actually it IS composed
    // so inner, agent1, agent2 are all agents (3 composed skills)
    assert.equal(stats.agents, 3);
    assert.equal(stats.skills, 2); // a, b
    // a is used by inner, agent1 (via inner), agent2 -> 3 agents
    // b is used by inner, agent1 (via inner) -> 2 agents
    assert.equal(stats.shared, 2); // both a and b are shared
    // a: (3-1)*2 = 4, b: (2-1)*1 = 1
    assert.equal(stats.linesDeduplicated, 5);
  });

  it("returns zero agents when config has no composed skills", () => {
    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Plan body");

    const stats = computeStats(config, bodies);

    assert.equal(stats.agents, 0);
    assert.equal(stats.skills, 0);
    assert.equal(stats.shared, 0);
    assert.equal(stats.linesDeduplicated, 0);
  });
});

describe("compile with goose target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs SKILL.md files under skills/ subdirectory", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "goose");

    assert.equal(results.length, 1);
    assert.equal(results[0].name, "bundle");
    assert.equal(results[0].path, join(outDir, "skills", "bundle", "SKILL.md"));
    assert.ok(existsSync(results[0].path));
  });

  it("outputs standard Agent Skills frontmatter", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "goose");

    const content = readFileSync(join(outDir, "skills", "bundle", "SKILL.md"), "utf-8");
    assert.ok(content.includes("<!-- Generated by skillfold v0.0.0"));
    assert.ok(content.includes("name: bundle"));
    assert.ok(content.includes("description: A bundle skill."));
    assert.ok(content.includes("Leaf body"));
  });
});

describe("compile with roo-code target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs skills, rules, and .roomodes", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "roo-code");

    const skillResult = results.find((r) => r.name === "bundle");
    assert.ok(skillResult);
    assert.equal(skillResult.path, join(outDir, "skills", "bundle", "SKILL.md"));

    const ruleResult = results.find((r) => r.name === "rule-bundle");
    assert.ok(ruleResult);
    assert.equal(ruleResult.path, join(outDir, "rules", "bundle.md"));

    const roomodesResult = results.find((r) => r.name === "roomodes");
    assert.ok(roomodesResult);
  });

  it("generates valid .roomodes JSON with custom modes", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "roo-code");

    const roomodesPath = join(tmpDir, ".roomodes");
    assert.ok(existsSync(roomodesPath));
    const roomodesContent = readFileSync(roomodesPath, "utf-8");
    // Skip the provenance comment to parse JSON
    const jsonStart = roomodesContent.indexOf("{");
    const parsed = JSON.parse(roomodesContent.slice(jsonStart));
    assert.ok(Array.isArray(parsed.customModes));
    assert.equal(parsed.customModes.length, 1);
    assert.equal(parsed.customModes[0].slug, "bundle");
    assert.equal(parsed.customModes[0].roleDefinition, "A bundle skill.");
  });

  it("generates standalone orchestrator rule when team has no orchestrator key", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: [] },
      ],
    };

    const config: Config = {
      name: "roo-test",
      skills: {
        worker: { path: "./skills/worker" },
      },
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "roo-code");

    const orchResult = results.find((r) => r.name === "rule-orchestrator");
    assert.ok(orchResult);
    assert.equal(orchResult.path, join(outDir, "rules", "orchestrator.md"));
    assert.ok(existsSync(orchResult.path));
    const content = readFileSync(orchResult.path, "utf-8");
    assert.ok(content.includes("# Orchestrator: roo-test"));
  });
});

describe("compile with kiro target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs skills and steering files", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "kiro");

    const skillResult = results.find((r) => r.name === "bundle");
    assert.ok(skillResult);
    assert.equal(skillResult.path, join(outDir, "skills", "bundle", "SKILL.md"));

    const steeringResult = results.find((r) => r.name === "steering-bundle");
    assert.ok(steeringResult);
    assert.equal(steeringResult.path, join(outDir, "steering", "bundle.md"));
  });

  it("includes kiro frontmatter with inclusion: always", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "kiro");

    const content = readFileSync(join(outDir, "steering", "bundle.md"), "utf-8");
    assert.ok(content.includes("<!-- Generated by skillfold v0.0.0"));
    assert.ok(content.includes("inclusion: always"));
    assert.ok(content.includes("Leaf body"));
  });

  it("generates standalone orchestrator steering when team has no orchestrator key", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: [] },
      ],
    };

    const config: Config = {
      name: "kiro-test",
      skills: {
        worker: { path: "./skills/worker" },
      },
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "kiro");

    const orchResult = results.find((r) => r.name === "steering-orchestrator");
    assert.ok(orchResult);
    assert.equal(orchResult.path, join(outDir, "steering", "orchestrator.md"));
    assert.ok(existsSync(orchResult.path));
    const content = readFileSync(orchResult.path, "utf-8");
    assert.ok(content.includes("inclusion: always"));
    assert.ok(content.includes("# Orchestrator: kiro-test"));
  });
});

describe("compile with junie target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs skills and guideline files", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "junie");

    const skillResult = results.find((r) => r.name === "bundle");
    assert.ok(skillResult);
    assert.equal(skillResult.path, join(outDir, "skills", "bundle", "SKILL.md"));

    const guidelineResult = results.find((r) => r.name === "guideline-bundle");
    assert.ok(guidelineResult);
    assert.equal(guidelineResult.path, join(outDir, "bundle_guidelines.md"));
  });

  it("guidelines are plain markdown without frontmatter", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "junie");

    const content = readFileSync(join(outDir, "bundle_guidelines.md"), "utf-8");
    assert.ok(content.includes("<!-- Generated by skillfold v0.0.0"));
    assert.ok(content.includes("Leaf body"));
    // Should NOT contain frontmatter delimiters (--- at start of line)
    const lines = content.split("\n");
    const frontmatterLines = lines.filter((l) => l === "---");
    assert.equal(frontmatterLines.length, 0, "Junie guidelines should not have YAML frontmatter");
  });

  it("generates standalone orchestrator guideline when team has no orchestrator key", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: [] },
      ],
    };

    const config: Config = {
      name: "junie-test",
      skills: {
        worker: { path: "./skills/worker" },
      },
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "junie");

    const orchResult = results.find((r) => r.name === "guideline-orchestrator");
    assert.ok(orchResult);
    assert.equal(orchResult.path, join(outDir, "orchestrator_guidelines.md"));
    assert.ok(existsSync(orchResult.path));
    const content = readFileSync(orchResult.path, "utf-8");
    assert.ok(content.includes("# Orchestrator: junie-test"));
    // No frontmatter
    const lines = content.split("\n");
    const frontmatterLines = lines.filter((l) => l === "---");
    assert.equal(frontmatterLines.length, 0);
  });
});
