import { afterEach, describe, it } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

import type { Config } from "./config.js";
import { CompileError } from "./errors.js";
import { check, compile } from "./compiler.js";
import type { Graph } from "./graph.js";
import type { StateSchema } from "./state.js";

function makeTmpDir(): string {
  const dir = join(tmpdir(), `skillfold-compiler-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

describe("compile", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("single composed skill produces file with frontmatter and bodies joined by double newline", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        lint: { path: "./skills/lint" },
        format: { path: "./skills/format" },
        quality: { compose: ["lint", "format"], description: "Runs quality checks." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("lint", "Run the linter.");
    bodies.set("format", "Format the code.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.equal(results.length, 1);
    assert.equal(results[0].name, "quality");

    const content = readFileSync(results[0].path, "utf-8");
    assert.ok(content.startsWith("<!-- Generated by skillfold v0.0.0 from test (test.yaml). Do not edit directly. -->\n"));
    assert.ok(content.includes("name: quality"));
    assert.ok(content.includes("description: Runs quality checks."));
    assert.ok(content.includes("Run the linter.\n\nFormat the code.\n"));
  });

  it("recursive composition flattens to all leaf bodies in correct order", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        a: { path: "./skills/a" },
        b: { path: "./skills/b" },
        c: { path: "./skills/c" },
        inner: { compose: ["a", "b"], description: "Inner skill." },
        outer: { compose: ["inner", "c"], description: "Outer skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("a", "Body A");
    bodies.set("b", "Body B");
    bodies.set("c", "Body C");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");

    const outerResult = results.find((r) => r.name === "outer");
    assert.ok(outerResult);

    const content = readFileSync(outerResult.path, "utf-8");
    assert.ok(content.includes("Body A\n\nBody B\n\nBody C\n"));
  });

  it("output files at {skill-name}/SKILL.md", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.equal(results[0].path, join(outDir, "bundle", "SKILL.md"));
    assert.ok(existsSync(join(outDir, "bundle", "SKILL.md")));
  });

  it("atomic skills do not produce output files", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.ok(!existsSync(join(outDir, "leaf")));
  });

  it("unknown skill reference throws CompileError", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        broken: { compose: ["nonexistent"], description: "Broken skill." },
      },
    };

    const bodies = new Map<string, string>();

    assert.throws(() => compile(config, bodies, outDir, "0.0.0", "test.yaml"), (err: unknown) => {
      assert.ok(err instanceof CompileError);
      assert.match(err.message, /Unknown skill/);
      return true;
    });
  });

  it("missing body for atomic skill throws CompileError", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    // Intentionally omit body for "leaf"
    const bodies = new Map<string, string>();

    assert.throws(() => compile(config, bodies, outDir, "0.0.0", "test.yaml"), (err: unknown) => {
      assert.ok(err instanceof CompileError);
      assert.match(err.message, /No resolved body for atomic skill/);
      return true;
    });
  });

  it("config with team and orchestrator key appends orchestrator to composed skill output", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const state: StateSchema = {
      types: {},
      fields: {
        goal: { type: { kind: "primitive", value: "string" } },
      },
    };

    const graph: Graph = {
      nodes: [
        { skill: "strategy", reads: [], writes: ["state.goal"], then: "lead" },
        { skill: "lead", reads: ["state.goal"], writes: [] },
      ],
    };

    const config: Config = {
      name: "test",
      skills: {
        strategy: { path: "./skills/strategy" },
        lead: { path: "./skills/lead" },
        pipeline: { compose: ["strategy", "lead"], description: "Runs the pipeline." },
      },
      state,
      team: {
        orchestrator: "pipeline",
        flow: graph,
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("strategy", "Strategy body.");
    bodies.set("lead", "Lead body.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");

    // The pipeline/SKILL.md should exist (from composed skill output)
    const pipelineResult = results.find((r) => r.name === "pipeline");
    assert.ok(pipelineResult);
    assert.equal(pipelineResult.path, join(outDir, "pipeline", "SKILL.md"));

    const content = readFileSync(pipelineResult.path, "utf-8");
    // Should contain provenance + frontmatter
    assert.ok(content.startsWith("<!-- Generated by skillfold v0.0.0 from test (test.yaml). Do not edit directly. -->\n---\n"));
    assert.ok(content.includes("name: pipeline"));
    assert.ok(content.includes("description: Runs the pipeline."));
    // Should contain the composed bodies
    assert.ok(content.includes("Strategy body."));
    assert.ok(content.includes("Lead body."));
    // Should also contain orchestrator content
    assert.ok(content.includes("# Orchestrator: test"));
    assert.ok(content.includes("## Execution Plan"));
    assert.ok(content.includes("### Step 1: strategy"));

    // No standalone orchestrator directory should exist
    assert.ok(!existsSync(join(outDir, "orchestrator")));
  });

  it("config with team but no orchestrator key generates standalone orchestrator/SKILL.md", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: [] },
      ],
    };

    const config: Config = {
      name: "standalone-test",
      skills: {
        worker: { path: "./skills/worker" },
      },
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");

    const orchResult = results.find((r) => r.name === "orchestrator");
    assert.ok(orchResult);
    assert.equal(orchResult.path, join(outDir, "orchestrator", "SKILL.md"));

    const content = readFileSync(orchResult.path, "utf-8");
    assert.ok(content.includes("# Orchestrator: standalone-test"));
    assert.ok(content.includes("### Step 1: worker"));
  });

  it("frontmatter contains correct name and description", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        agent: { compose: ["leaf"], description: "An agent that does things." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf content.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml");
    const content = readFileSync(results[0].path, "utf-8");

    // Verify provenance + frontmatter structure
    const lines = content.split("\n");
    assert.equal(lines[0], "<!-- Generated by skillfold v0.0.0 from test (test.yaml). Do not edit directly. -->");
    assert.equal(lines[1], "---");
    assert.equal(lines[2], "name: agent");
    assert.equal(lines[3], "description: An agent that does things.");
    assert.equal(lines[4], "---");
  });

  it("--target skill produces same output as default", () => {
    tmpDir = makeTmpDir();
    const outDir1 = join(tmpDir, "default");
    const outDir2 = join(tmpDir, "skill");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results1 = compile(config, bodies, outDir1, "0.0.0", "test.yaml");
    const results2 = compile(config, bodies, outDir2, "0.0.0", "test.yaml", "skill");

    assert.equal(results1.length, results2.length);
    const content1 = readFileSync(results1[0].path, "utf-8");
    const content2 = readFileSync(results2[0].path, "utf-8");
    assert.equal(content1, content2);
  });
});

describe("compile with claude-code target", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("outputs skills under skills/ subdirectory", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const skillResult = results.find((r) => r.name === "bundle" && r.path.includes("skills"));
    assert.ok(skillResult);
    assert.equal(skillResult.path, join(outDir, "skills", "bundle", "SKILL.md"));
    assert.ok(existsSync(skillResult.path));
  });

  it("outputs agent markdown files under agents/ subdirectory", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const agentResult = results.find((r) => r.path.includes("agents"));
    assert.ok(agentResult);
    assert.equal(agentResult.path, join(outDir, "agents", "bundle.md"));
    assert.ok(existsSync(agentResult.path));
  });

  it("agent files contain frontmatter and body", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const content = readFileSync(join(outDir, "agents", "bundle.md"), "utf-8");
    assert.ok(content.includes("name: bundle"));
    assert.ok(content.includes("description: A bundle skill."));
    assert.ok(content.includes("Leaf body"));
  });

  it("produces both skills and agents for config with team flow", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    // Should have skills (planner, worker, orchestrator) + agents (planner, worker)
    const skillPaths = results.filter((r) => r.path.includes("/skills/"));
    const agentPaths = results.filter((r) => r.path.includes("/agents/"));

    assert.ok(skillPaths.length >= 2);
    assert.ok(agentPaths.length >= 2);
  });

  it("generates run-pipeline command when team flow exists", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: [] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "test-pipeline",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const cmdResult = results.find((r) => r.path.includes("commands"));
    assert.ok(cmdResult);
    assert.equal(cmdResult.path, join(outDir, "commands", "run-pipeline.md"));
    assert.ok(existsSync(cmdResult.path));
  });

  it("does not generate run-pipeline command when team flow is absent", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config: Config = {
      name: "test",
      skills: {
        leaf: { path: "./skills/leaf" },
        bundle: { compose: ["leaf"], description: "A bundle skill." },
      },
    };

    const bodies = new Map<string, string>();
    bodies.set("leaf", "Leaf body");

    const results = compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const cmdResult = results.find((r) => r.path.includes("commands"));
    assert.equal(cmdResult, undefined);
    assert.ok(!existsSync(join(outDir, "commands")));
  });

  it("run-pipeline command includes execution steps matching the flow", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
        { skill: "worker", reads: ["state.plan"], writes: ["state.result"] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
        result: { type: { kind: "primitive", value: "string" } },
      },
    };

    const config: Config = {
      name: "flow-test",
      skills: {
        planning: { path: "./skills/planning" },
        working: { path: "./skills/working" },
        planner: { compose: ["planning"], description: "Plans." },
        worker: { compose: ["working"], description: "Works." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");
    bodies.set("working", "Working body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const content = readFileSync(join(outDir, "commands", "run-pipeline.md"), "utf-8");
    assert.ok(content.includes("## Execution Plan"));
    assert.ok(content.includes("### Step 1: planner"));
    assert.ok(content.includes("### Step 2: worker"));
    assert.ok(content.includes("Invoke **planner**"));
    assert.ok(content.includes("Invoke **worker**"));
  });

  it("run-pipeline command includes state table when state is defined", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "planner", reads: [], writes: ["state.plan"] },
      ],
    };

    const state: StateSchema = {
      types: {},
      fields: {
        plan: { type: { kind: "primitive", value: "string" } },
        count: { type: { kind: "primitive", value: "number" } },
      },
    };

    const config: Config = {
      name: "state-test",
      skills: {
        planning: { path: "./skills/planning" },
        planner: { compose: ["planning"], description: "Plans." },
      },
      state,
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();
    bodies.set("planning", "Planning body.");

    compile(config, bodies, outDir, "0.0.0", "test.yaml", "claude-code");

    const content = readFileSync(join(outDir, "commands", "run-pipeline.md"), "utf-8");
    assert.ok(content.includes("## State"));
    assert.ok(content.includes("| plan | string |"));
    assert.ok(content.includes("| count | number |"));
  });
});

describe("check", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  function makeConfig(): { config: Config; bodies: Map<string, string> } {
    const config: Config = {
      name: "test",
      skills: {
        lint: { path: "./skills/lint" },
        format: { path: "./skills/format" },
        quality: { compose: ["lint", "format"], description: "Runs quality checks." },
      },
    };
    const bodies = new Map<string, string>();
    bodies.set("lint", "Run the linter.");
    bodies.set("format", "Format the code.");
    return { config, bodies };
  }

  it("returns ok when compiled output matches on disk", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");
    const { config, bodies } = makeConfig();

    compile(config, bodies, outDir, "0.0.0", "test.yaml");
    const results = check(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.equal(results.length, 1);
    assert.equal(results[0].name, "quality");
    assert.equal(results[0].status, "ok");
  });

  it("returns stale when on-disk content differs", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");
    const { config, bodies } = makeConfig();

    compile(config, bodies, outDir, "0.0.0", "test.yaml");
    writeFileSync(join(outDir, "quality", "SKILL.md"), "old content", "utf-8");
    const results = check(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.equal(results.length, 1);
    assert.equal(results[0].status, "stale");
  });

  it("returns missing when output file does not exist", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");
    const { config, bodies } = makeConfig();

    const results = check(config, bodies, outDir, "0.0.0", "test.yaml");

    assert.equal(results.length, 1);
    assert.equal(results[0].status, "missing");
  });

  it("checks orchestrator output when team is defined", () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const graph: Graph = {
      nodes: [
        { skill: "worker", reads: [], writes: [] },
      ],
    };

    const config: Config = {
      name: "orch-test",
      skills: {
        worker: { path: "./skills/worker" },
      },
      team: { flow: graph },
    };

    const bodies = new Map<string, string>();

    compile(config, bodies, outDir, "0.0.0", "test.yaml");
    const results = check(config, bodies, outDir, "0.0.0", "test.yaml");

    const orchResult = results.find((r) => r.name === "orchestrator");
    assert.ok(orchResult);
    assert.equal(orchResult.status, "ok");
  });
});
