import assert from "node:assert/strict";
import { describe, it } from "node:test";

import {
  composeBody,
  composeOrder,
  defaultComposeDescription,
  generateComposedSkill,
} from "./compose.js";
import { parseFrontmatter } from "./skill.js";

describe("composeBody", () => {
  it("joins trimmed parts with blank lines", () => {
    assert.equal(composeBody(["# A\n\n", "\n# B"]), "# A\n\n# B");
  });

  it("drops empty parts", () => {
    assert.equal(composeBody(["# A", "   ", "# B"]), "# A\n\n# B");
  });
});

describe("generateComposedSkill", () => {
  const entry = { description: "Review with tests.", use: ["review", "testing"] };
  const inputs = [
    { description: "Reviews code.", body: "# Review\n\nLook closely." },
    { description: "Writes tests.", body: "# Testing\n\nTest well." },
  ];

  it("produces a single SKILL.md", () => {
    const skill = generateComposedSkill("reviewer", entry, inputs);
    assert.deepEqual(
      skill.files.map((f) => f.path),
      ["SKILL.md"]
    );
  });

  it("has valid frontmatter and provenance", () => {
    const skill = generateComposedSkill("reviewer", entry, inputs);
    const text = skill.files[0].content.toString("utf-8");
    const { attrs, body } = parseFrontmatter(text);
    assert.equal(attrs.name, "reviewer");
    assert.equal(attrs.description, "Review with tests.");
    assert.match(body, /Generated by skillfold/);
    assert.match(body, /Composed from: review, testing/);
    assert.match(body, /# Review/);
    assert.match(body, /# Testing/);
    assert.ok(text.indexOf("# Review") < text.indexOf("# Testing"));
  });

  it("defaults the description", () => {
    const skill = generateComposedSkill("reviewer", { use: ["a", "b"] }, inputs);
    assert.equal(skill.description, "Composed skill combining a, b.");
  });

  it("escapes tricky descriptions in frontmatter", () => {
    const skill = generateComposedSkill(
      "tricky",
      { description: 'Has: colons, "quotes" and #hashes', use: ["a"] },
      [inputs[0]]
    );
    const { attrs } = parseFrontmatter(skill.files[0].content.toString("utf-8"));
    assert.equal(attrs.description, 'Has: colons, "quotes" and #hashes');
  });
});

describe("composeOrder", () => {
  it("puts dependencies before dependents", () => {
    const order = composeOrder({
      outer: { use: ["inner", "a"] },
      inner: { use: ["a"] },
    });
    assert.ok(order.indexOf("inner") < order.indexOf("outer"));
  });

  it("handles chains", () => {
    const order = composeOrder({
      c: { use: ["b"] },
      b: { use: ["a-skill"] },
      a: { use: ["c"] },
    });
    assert.deepEqual(order, ["b", "c", "a"]);
  });
});
