import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { type Config, isComposed } from "./config.js";
import { CompileError } from "./errors.js";
import { generateOrchestrator } from "./orchestrator.js";

function expand(
  name: string,
  config: Config,
  bodies: Map<string, string>,
  seen: Set<string>
): string[] {
  if (seen.has(name)) {
    throw new CompileError(name, "Circular composition during expansion");
  }

  const skill = config.skills[name];
  if (!skill) {
    throw new CompileError(name, "Unknown skill");
  }

  if (!isComposed(skill)) {
    const body = bodies.get(name);
    if (body === undefined) {
      throw new CompileError(name, "No resolved body for atomic skill");
    }
    return [body];
  }

  seen.add(name);
  const parts: string[] = [];
  for (const ref of skill.compose) {
    parts.push(...expand(ref, config, bodies, new Set(seen)));
  }
  return parts;
}

function formatFrontmatter(name: string, description: string): string {
  return `---\nname: ${name}\ndescription: ${description}\n---\n`;
}

function formatProvenance(configName: string): string {
  return `<!-- Generated by skillfold from ${configName}. Do not edit directly. -->\n`;
}

export interface GenerateResult {
  name: string;
  path: string;
  content: string;
}

export interface CompileResult {
  name: string;
  path: string;
}

export interface CheckResult {
  name: string;
  path: string;
  status: "ok" | "stale" | "missing";
}

export function generate(
  config: Config,
  bodies: Map<string, string>,
  outDir: string
): GenerateResult[] {
  const results: GenerateResult[] = [];

  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;

    const parts = expand(name, config, bodies, new Set());
    const body = parts.join("\n\n");
    const outPath = join(outDir, name, "SKILL.md");

    const output = formatFrontmatter(name, skill.description) + "\n" + body + "\n";
    results.push({ name, path: outPath, content: output });
  }

  if (config.team) {
    const orchestratorMd = generateOrchestrator(config);

    if (config.team.orchestrator) {
      const target = results.find((r) => r.name === config.team!.orchestrator);
      if (target) {
        target.content = target.content + "\n" + orchestratorMd;
      }
    } else {
      const outPath = join(outDir, "orchestrator", "SKILL.md");
      results.push({ name: "orchestrator", path: outPath, content: orchestratorMd });
    }
  }

  const provenance = formatProvenance(config.name);
  for (const result of results) {
    result.content = provenance + result.content;
  }

  return results;
}

export function compile(
  config: Config,
  bodies: Map<string, string>,
  outDir: string
): CompileResult[] {
  mkdirSync(outDir, { recursive: true });

  const generated = generate(config, bodies, outDir);

  for (const result of generated) {
    mkdirSync(join(outDir, result.name), { recursive: true });
    writeFileSync(result.path, result.content, "utf-8");
  }

  return generated.map(({ name, path }) => ({ name, path }));
}

export function check(
  config: Config,
  bodies: Map<string, string>,
  outDir: string
): CheckResult[] {
  const generated = generate(config, bodies, outDir);
  const results: CheckResult[] = [];

  for (const result of generated) {
    if (!existsSync(result.path)) {
      results.push({ name: result.name, path: result.path, status: "missing" });
      continue;
    }

    const existing = readFileSync(result.path, "utf-8");
    if (existing === result.content) {
      results.push({ name: result.name, path: result.path, status: "ok" });
    } else {
      results.push({ name: result.name, path: result.path, status: "stale" });
    }
  }

  return results;
}
