import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

import { generateAgents, generateRunCommand } from "./agent.js";
import { type Config, isAtomic, isComposed } from "./config.js";
import { CompileError } from "./errors.js";
import { generateOrchestrator } from "./orchestrator.js";

export type CompileTarget = "skill" | "claude-code";

function expand(
  name: string,
  config: Config,
  bodies: Map<string, string>,
  seen: Set<string>
): string[] {
  if (seen.has(name)) {
    throw new CompileError(name, "Circular composition during expansion");
  }

  const skill = config.skills[name];
  if (!skill) {
    throw new CompileError(name, "Unknown skill");
  }

  if (!isComposed(skill)) {
    const body = bodies.get(name);
    if (body === undefined) {
      throw new CompileError(name, "No resolved body for atomic skill");
    }
    return [body];
  }

  seen.add(name);
  const parts: string[] = [];
  for (const ref of skill.compose) {
    parts.push(...expand(ref, config, bodies, new Set(seen)));
  }
  return parts;
}

/**
 * Walk a skill's composition tree and collect the names of all atomic skills
 * it expands to (in order, with duplicates).
 */
function expandAtomicNames(
  name: string,
  config: Config,
  seen: Set<string>,
): string[] {
  if (seen.has(name)) return [];

  const skill = config.skills[name];
  if (!skill) return [];

  if (!isComposed(skill)) {
    return [name];
  }

  seen.add(name);
  const names: string[] = [];
  for (const ref of skill.compose) {
    names.push(...expandAtomicNames(ref, config, new Set(seen)));
  }
  return names;
}

export interface CompileStats {
  agents: number;
  skills: number;
  shared: number;
  linesDeduplicated: number;
}

export function computeStats(
  config: Config,
  bodies: Map<string, string>,
): CompileStats {
  const composedEntries = Object.entries(config.skills).filter(
    ([, skill]) => isComposed(skill),
  );

  // For each composed skill (agent), find which atomic skills it uses
  const agentAtomics = new Map<string, Set<string>>();
  for (const [name] of composedEntries) {
    const atomicNames = expandAtomicNames(name, config, new Set());
    agentAtomics.set(name, new Set(atomicNames));
  }

  // Collect all unique atomic skills and count how many agents use each
  const usageCount = new Map<string, number>();
  for (const atomics of agentAtomics.values()) {
    for (const atomic of atomics) {
      usageCount.set(atomic, (usageCount.get(atomic) ?? 0) + 1);
    }
  }

  const agents = composedEntries.length;
  const skills = usageCount.size;
  const shared = [...usageCount.values()].filter((count) => count >= 2).length;

  // Lines deduplicated: for each atomic skill used by N agents,
  // (N - 1) * lineCount of that skill's body
  let linesDeduplicated = 0;
  for (const [atomic, count] of usageCount) {
    if (count <= 1) continue;
    const body = bodies.get(atomic);
    if (body === undefined) continue;
    const lineCount = body.split("\n").length;
    linesDeduplicated += (count - 1) * lineCount;
  }

  return { agents, skills, shared, linesDeduplicated };
}

function formatFrontmatter(name: string, description: string): string {
  return `---\nname: ${name}\ndescription: ${description}\n---\n`;
}

function formatProvenance(configName: string, version: string, configFile: string): string {
  return `<!-- Generated by skillfold v${version} from ${configName} (${configFile}). Do not edit directly. -->\n`;
}

export interface GenerateResult {
  name: string;
  path: string;
  content: string;
}

export interface CompileResult {
  name: string;
  path: string;
}

export interface CheckResult {
  name: string;
  path: string;
  status: "ok" | "stale" | "missing";
}

export function generate(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string
): GenerateResult[] {
  const results: GenerateResult[] = [];

  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;

    const parts = expand(name, config, bodies, new Set());
    const body = parts.join("\n\n");
    const outPath = join(outDir, name, "SKILL.md");

    const output = formatFrontmatter(name, skill.description) + "\n" + body + "\n";
    results.push({ name, path: outPath, content: output });
  }

  if (config.team) {
    const orchestratorMd = generateOrchestrator(config);

    if (config.team.orchestrator) {
      const target = results.find((r) => r.name === config.team!.orchestrator);
      if (target) {
        target.content = target.content + "\n" + orchestratorMd;
      }
    } else {
      const outPath = join(outDir, "orchestrator", "SKILL.md");
      results.push({ name: "orchestrator", path: outPath, content: orchestratorMd });
    }
  }

  const provenance = formatProvenance(config.name, version, configFile);
  for (const result of results) {
    result.content = provenance + result.content;
  }

  return results;
}

/**
 * Build a map of composed skill name -> expanded body text.
 * Used by agent generation to include composed skill content.
 */
export function expandComposedBodies(
  config: Config,
  bodies: Map<string, string>,
): Map<string, string> {
  const composedBodies = new Map<string, string>();
  for (const [name, skill] of Object.entries(config.skills)) {
    if (!isComposed(skill)) continue;
    const parts = expand(name, config, bodies, new Set());
    composedBodies.set(name, parts.join("\n\n"));
  }
  return composedBodies;
}

/**
 * Generate output for claude-code target: skills in skills/ subdirectory
 * and agent markdown files in agents/ subdirectory.
 */
export function generateClaudeCode(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
): GenerateResult[] {
  const results: GenerateResult[] = [];

  // Generate skills under skills/ subdirectory
  const skillResults = generate(config, bodies, outDir, version, configFile);
  for (const result of skillResults) {
    // Rewrite paths: {outDir}/{name}/SKILL.md -> {outDir}/skills/{name}/SKILL.md
    result.path = join(outDir, "skills", result.name, "SKILL.md");
    results.push(result);
  }

  // Generate agent markdown files
  const composedBodies = expandComposedBodies(config, bodies);
  const agentResults = generateAgents(
    config,
    composedBodies,
    outDir,
    version,
    configFile,
  );
  for (const agent of agentResults) {
    results.push(agent);
  }

  // Generate run-pipeline command if team flow exists
  const runCommand = generateRunCommand(config, version, configFile);
  if (runCommand) {
    runCommand.path = join(outDir, "commands", "run-pipeline.md");
    results.push(runCommand);
  }

  return results;
}

function writeResults(results: GenerateResult[]): void {
  for (const result of results) {
    mkdirSync(dirname(result.path), { recursive: true });
    writeFileSync(result.path, result.content, "utf-8");
  }
}

export function compile(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
  target: CompileTarget = "skill",
): CompileResult[] {
  mkdirSync(outDir, { recursive: true });

  const generated =
    target === "claude-code"
      ? generateClaudeCode(config, bodies, outDir, version, configFile)
      : generate(config, bodies, outDir, version, configFile);

  writeResults(generated);

  return generated.map(({ name, path }) => ({ name, path }));
}

export function check(
  config: Config,
  bodies: Map<string, string>,
  outDir: string,
  version: string,
  configFile: string,
  target: CompileTarget = "skill",
): CheckResult[] {
  const generated =
    target === "claude-code"
      ? generateClaudeCode(config, bodies, outDir, version, configFile)
      : generate(config, bodies, outDir, version, configFile);
  const results: CheckResult[] = [];

  for (const result of generated) {
    if (!existsSync(result.path)) {
      results.push({ name: result.name, path: result.path, status: "missing" });
      continue;
    }

    const existing = readFileSync(result.path, "utf-8");
    if (existing === result.content) {
      results.push({ name: result.name, path: result.path, status: "ok" });
    } else {
      results.push({ name: result.name, path: result.path, status: "stale" });
    }
  }

  return results;
}
