import { afterEach, describe, it } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, rmSync } from "node:fs";
import { dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath } from "node:url";

import { parseRawConfig, readConfig, validateAndBuild } from "./config.js";
import { compile } from "./compiler.js";
import { listPipeline } from "./list.js";
import { generateOrchestrator } from "./orchestrator.js";
import { resolveSkills } from "./resolver.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixtureDir = join(__dirname, "..", "test", "fixtures", "dev-pipeline");
const configPath = join(fixtureDir, "skillfold.yaml");

function makeTmpDir(): string {
  const dir = join(
    tmpdir(),
    `skillfold-e2e-test-${Date.now()}-${Math.random().toString(36).slice(2)}`
  );
  mkdirSync(dir, { recursive: true });
  return dir;
}

/**
 * Assert that all substrings appear in content, in the given order.
 * Reports which substring failed and its expected position relative to the previous match.
 */
function assertOrderedSubstrings(content: string, substrings: string[]): void {
  let lastIndex = -1;
  for (const sub of substrings) {
    const idx = content.indexOf(sub, lastIndex + 1);
    assert.ok(
      idx > lastIndex,
      `Expected "${sub}" to appear after index ${lastIndex} in content, but ${idx === -1 ? "it was not found" : `found at ${idx}`}`
    );
    lastIndex = idx;
  }
}

describe("e2e: dev-pipeline", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("reads config, resolves skills, and compiles without errors", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    const results = compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    assert.ok(results.length > 0);
  });

  it("produces output directories for all composed skills", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const expected = [
      "strategy/SKILL.md",
      "tech-lead/SKILL.md",
      "senior-engineer/SKILL.md",
      "reviewer/SKILL.md",
      "orchestrator/SKILL.md",
    ];

    for (const file of expected) {
      assert.ok(
        existsSync(join(outDir, file)),
        `Expected output file "${file}" to exist`
      );
    }
  });

  it("strategy/SKILL.md contains frontmatter and Strategic Thinking then Slack Integration", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "strategy", "SKILL.md"), "utf-8");
    assert.ok(content.startsWith("<!-- Generated by skillfold v"));
    assert.ok(content.includes("name: strategy"));
    assert.ok(content.includes("description: Defines the strategic goal"));
    assertOrderedSubstrings(content, [
      "Strategic Thinking",
      "Slack Integration",
    ]);
  });

  it("tech-lead/SKILL.md contains all four skills in order", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "tech-lead", "SKILL.md"), "utf-8");
    assertOrderedSubstrings(content, [
      "Strategic Thinking",
      "Task Decomposition",
      "Slack Integration",
      "Jira Integration",
    ]);
  });

  it("senior-engineer/SKILL.md contains Task Decomposition then Code Generation", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "senior-engineer", "SKILL.md"), "utf-8");
    assertOrderedSubstrings(content, [
      "Task Decomposition",
      "Code Generation",
    ]);
  });

  it("reviewer/SKILL.md contains Code Review", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "reviewer", "SKILL.md"), "utf-8");
    assert.ok(
      content.includes("Code Review"),
      "reviewer/SKILL.md should contain Code Review"
    );
  });

  it("orchestrator/SKILL.md contains composed bodies before orchestrator plan", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "orchestrator", "SKILL.md"), "utf-8");

    // Composed bodies (Slack, Confluence, Jira) should appear before the orchestrator header
    assertOrderedSubstrings(content, [
      "Slack Integration",
      "Confluence Integration",
      "Jira Integration",
      "# Orchestrator: dev-pipeline",
    ]);
  });

  it("orchestrator/SKILL.md contains pipeline header and description", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "orchestrator", "SKILL.md"), "utf-8");

    assert.ok(content.includes("# Orchestrator: dev-pipeline"));
    assert.ok(content.includes("**dev-pipeline** pipeline"));
  });

  it("orchestrator/SKILL.md contains state table with correct fields and locations", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "orchestrator", "SKILL.md"), "utf-8");

    assert.ok(content.includes("## State"));
    assert.ok(content.includes("| Field | Type | Location |"));
    assert.ok(
      content.includes("| goal | string | slack: dev-pipeline-channel |")
    );
    assert.ok(
      content.includes(
        "| plan | string | slack: dev-pipeline-channel (reply) |"
      )
    );
    assert.ok(
      content.includes("| tasks | list<Task> | jira: DEV/dev-board |")
    );
  });

  it("orchestrator/SKILL.md contains execution plan with correct steps", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "orchestrator", "SKILL.md"), "utf-8");

    assert.ok(content.includes("## Execution Plan"));

    // Step 1: strategy
    assert.ok(content.includes("### Step 1: strategy"));
    assert.ok(content.includes("Invoke **strategy**."));
    assert.ok(content.includes("Writes: `state.goal`"));
    assert.ok(content.includes("Then: proceed to step 2."));

    // Step 2: tech-lead
    assert.ok(content.includes("### Step 2: tech-lead"));
    assert.ok(content.includes("Invoke **tech-lead**."));
    assert.ok(content.includes("Reads: `state.goal`"));
    assert.ok(content.includes("Writes: `state.plan`, `state.tasks`"));
    assert.ok(content.includes("Then: proceed to step 3."));

    // Step 3: map over state.tasks
    assert.ok(content.includes("### Step 3: map over state.tasks"));
    assert.ok(
      content.includes(
        "For each item in `state.tasks` (as `task`), run the following subgraph:"
      )
    );
  });

  it("orchestrator/SKILL.md contains map subgraph steps with correct sub-numbering", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "orchestrator", "SKILL.md"), "utf-8");

    // Step 3.1: senior-engineer
    assert.ok(content.includes("#### Step 3.1: senior-engineer"));
    assert.ok(content.includes("Invoke **senior-engineer**."));
    assert.ok(content.includes("Reads: `task.description`"));
    assert.ok(content.includes("Writes: `task.output`"));
    assert.ok(content.includes("Then: proceed to step 3.2."));

    // Step 3.2: reviewer
    assert.ok(content.includes("#### Step 3.2: reviewer"));
    assert.ok(content.includes("Invoke **reviewer**."));
    assert.ok(content.includes("Reads: `task.output`"));
    assert.ok(content.includes("Writes: `task.approved`"));
  });

  it("orchestrator/SKILL.md contains conditional branches for reviewer", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "dist");

    const config = readConfig(configPath);
    const bodies = await resolveSkills(config, fixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "orchestrator", "SKILL.md"), "utf-8");

    assert.ok(
      content.includes("- If `task.approved == false`: go to step 3.1")
    );
    assert.ok(content.includes("- If `task.approved == true`: end"));
  });
});

const asyncFixtureDir = join(__dirname, "..", "test", "fixtures", "async-pipeline");
const asyncConfigPath = join(asyncFixtureDir, "skillfold.yaml");

describe("e2e: async-pipeline", () => {
  let asyncTmpDir: string | undefined;

  afterEach(() => {
    if (asyncTmpDir) {
      rmSync(asyncTmpDir, { recursive: true, force: true });
      asyncTmpDir = undefined;
    }
  });

  it("config round-trips through readConfig with async nodes", () => {
    const config = readConfig(asyncConfigPath);
    assert.equal(config.name, "async-pipeline");
    assert.ok(config.team);
    assert.equal(config.team.flow.nodes.length, 3);
  });

  it("inline config with async node parses and validates", () => {
    const raw = parseRawConfig(`
name: async-inline
skills:
  atomic:
    coding: ./skills/coding
  composed:
    engineer:
      compose: [coding]
      description: "Writes code."
state:
  direction:
    type: string
  code:
    type: string
team:
  flow:
    - owner:
        async: true
        writes: [state.direction]
        policy: block
      then: engineer
    - engineer:
        reads: [state.direction]
        writes: [state.code]
      then: end
`);
    const config = validateAndBuild(raw);

    const output = generateOrchestrator(config);
    assert.ok(output.includes("### Step 1: owner (async)"));
    assert.ok(output.includes("Check `state.direction` at its external location."));
    assert.ok(output.includes("wait for the external agent to provide it"));
    assert.ok(output.includes("### Step 2: engineer"));
    assert.ok(output.includes("Invoke **engineer**."));

    const listOutput = listPipeline(config);
    assert.ok(listOutput.includes("owner (async) -> engineer"));
    assert.ok(listOutput.includes("engineer -> end"));
  });

  it("reads config, resolves skills, and compiles without errors", async () => {
    asyncTmpDir = makeTmpDir();
    const outDir = join(asyncTmpDir, "dist");

    const config = readConfig(asyncConfigPath);
    const bodies = await resolveSkills(config, asyncFixtureDir);
    const results = compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    assert.ok(results.length > 0);

    // Async "owner" should NOT produce its own SKILL.md
    assert.ok(!existsSync(join(outDir, "owner", "SKILL.md")));

    // Engineer and reviewer should have SKILL.md files
    assert.ok(existsSync(join(outDir, "engineer", "SKILL.md")));
    assert.ok(existsSync(join(outDir, "reviewer", "SKILL.md")));
  });

  it("inline config with resource declarations renders resolved URLs", () => {
    const raw = parseRawConfig(`
name: resources-test
skills:
  atomic:
    github:
      path: ./skills/github
      resources:
        discussions: "https://github.com/org/repo/discussions"
        issues: "https://github.com/org/repo/issues"
        pull-requests: "https://github.com/org/repo/pulls"
    coding: ./skills/coding
  composed:
    engineer:
      compose: [coding]
      description: "Writes code."
    orchestrator:
      compose: [github]
      description: "Coordinates."
state:
  direction:
    type: string
    location:
      skill: github
      path: discussions/general
  tasks:
    type: string
    location:
      skill: github
      path: issues
  review:
    type: string
    location:
      skill: github
      path: pull-requests
      kind: review
team:
  orchestrator: orchestrator
  flow:
    - engineer:
        reads: [state.direction]
        writes: [state.tasks]
      then: end
`);
    const config = validateAndBuild(raw);
    const output = generateOrchestrator(config);

    // State table should have resolved URLs
    assert.ok(output.includes("https://github.com/org/repo/discussions/general"));
    assert.ok(output.includes("https://github.com/org/repo/issues"));
    assert.ok(output.includes("https://github.com/org/repo/pulls (review)"));
    // Should NOT contain abstract format
    assert.ok(!output.includes("github: discussions"));
  });

  it("orchestrator includes async step in execution plan", async () => {
    asyncTmpDir = makeTmpDir();
    const outDir = join(asyncTmpDir, "dist");

    const config = readConfig(asyncConfigPath);
    const bodies = await resolveSkills(config, asyncFixtureDir);
    compile(config, bodies, outDir, "0.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "orchestrator", "SKILL.md"), "utf-8");

    assert.ok(content.includes("### Step 1: owner (async)"));
    assert.ok(content.includes("Check `state.direction` at its external location."));
    assert.ok(content.includes("wait for the external agent to provide it before proceeding"));
    assert.ok(content.includes("### Step 2: engineer"));
    assert.ok(content.includes("Invoke **engineer**."));
    assert.ok(content.includes("### Step 3: reviewer"));
  });
});
