import assert from "node:assert/strict";
import { join } from "node:path";
import { after, describe, it } from "node:test";
import { writeFileSync } from "node:fs";

import { LockError } from "./errors.js";
import {
  emptyLockfile,
  lockfileProblems,
  readLockfile,
  serializeLockfile,
  writeLockfile,
  type Lockfile,
} from "./lock.js";
import { parseManifest } from "./manifest.js";
import { makeTmpDir } from "./testutil.js";

const tmp = makeTmpDir();
after(() => tmp.cleanup());

function sampleLock(): Lockfile {
  return {
    lockfileVersion: 1,
    skills: {
      remote: {
        source: "github:o/r/skills/remote@v1",
        resolved: `github:o/r/skills/remote@${"a".repeat(40)}`,
        integrity: "sha256-abc=",
      },
      local: { source: "./skills/local" },
    },
    compose: {
      both: { use: ["remote", "local"], integrity: "sha256-def=" },
    },
    rules: {},
    targets: ["claude"],
  };
}

describe("lockfile io", () => {
  it("roundtrips", () => {
    const path = join(tmp.path, "skillfold.lock");
    writeLockfile(path, sampleLock());
    const read = readLockfile(path);
    assert.deepEqual(read, sampleLock());
  });

  it("returns null when missing", () => {
    assert.equal(readLockfile(join(tmp.path, "missing.lock")), null);
  });

  it("serializes with a header and sorted keys", () => {
    const text = serializeLockfile(sampleLock());
    assert.match(text, /^# Generated by skillfold/);
    assert.ok(text.indexOf("local:") < text.indexOf("remote:"));
  });

  it("rejects unsupported versions", () => {
    const path = join(tmp.path, "bad.lock");
    writeFileSync(path, "lockfileVersion: 99\n");
    assert.throws(() => readLockfile(path), LockError);
  });

  it("rejects malformed entries", () => {
    const path = join(tmp.path, "bad2.lock");
    writeFileSync(path, "lockfileVersion: 1\nskills:\n  a:\n    resolved: x\n");
    assert.throws(() => readLockfile(path), /missing "source"/);
  });
});

describe("lockfileProblems", () => {
  const manifest = parseManifest(
    [
      "skills:",
      "  remote: github:o/r/skills/remote@v1",
      "  local: ./skills/local",
      "compose:",
      "  both:",
      "    use: [remote, local]",
    ].join("\n"),
    "t.yaml"
  );

  it("reports a missing lockfile", () => {
    const problems = lockfileProblems(manifest, null);
    assert.equal(problems.length, 1);
    assert.match(problems[0], /missing skillfold.lock/);
  });

  it("passes when in sync", () => {
    assert.deepEqual(lockfileProblems(manifest, sampleLock()), []);
  });

  it("reports manifest entries missing from the lock", () => {
    const lock = sampleLock();
    delete lock.skills.remote;
    assert.match(lockfileProblems(manifest, lock)[0], /"remote" is in the manifest but not/);
  });

  it("reports source changes", () => {
    const lock = sampleLock();
    lock.skills.remote.source = "github:o/r/skills/remote@v2";
    assert.match(lockfileProblems(manifest, lock)[0], /changed source/);
  });

  it("reports stale lock entries", () => {
    const lock = sampleLock();
    lock.skills.gone = { source: "./skills/gone" };
    assert.match(lockfileProblems(manifest, lock)[0], /in the lockfile but not the manifest/);
  });

  it("reports compose drift", () => {
    const lock = sampleLock();
    lock.compose.both.use = ["remote"];
    assert.match(lockfileProblems(manifest, lock)[0], /changed its "use" list/);
  });

  it("reports stale compose entries", () => {
    const lock = sampleLock();
    lock.compose.old = { use: ["remote"], integrity: "sha256-x=" };
    assert.match(
      lockfileProblems(manifest, lock)[0],
      /composed skill "old" is in the lockfile but not/
    );
  });
});

describe("emptyLockfile", () => {
  it("has version 1", () => {
    assert.equal(emptyLockfile().lockfileVersion, 1);
  });
});

describe("lockfile rules section", () => {
  it("roundtrips rules entries", () => {
    const lock = sampleLock();
    lock.rules["code-style"] = {
      source: "github:o/r/rules/code-style.md@v1",
      resolved: `github:o/r/rules/code-style.md@${"b".repeat(40)}`,
      integrity: "sha256-xyz=",
    };
    const path = join(tmp.path, "rules.lock");
    writeLockfile(path, lock);
    assert.deepEqual(readLockfile(path), lock);
  });

  it("omits the rules key when empty, so old lockfiles do not churn", () => {
    assert.ok(!serializeLockfile(sampleLock()).includes("rules:"));
  });

  it("reads pre-rules lockfiles as having no rules", () => {
    const path = join(tmp.path, "old.lock");
    writeLockfile(path, sampleLock());
    assert.deepEqual(readLockfile(path)!.rules, {});
  });

  it("reports manifest/lock drift for rules", () => {
    const manifest = parseManifest("rules:\n  style: ./rules/style.md", "t.yaml");
    const lock = sampleLock();
    // sampleLock has skills the manifest lacks; focus on the rules problems.
    const problems = lockfileProblems(manifest, lock).filter((p) => p.includes("rule"));
    assert.deepEqual(problems, ['rule "style" is in the manifest but not the lockfile']);

    lock.rules.style = { source: "./other/style.md" };
    const changed = lockfileProblems(manifest, lock).filter((p) => p.includes("rule"));
    assert.match(changed[0], /changed source/);
  });
});

describe("lockfile targets", () => {
  it("roundtrips non-default targets and omits the default", () => {
    const lock = sampleLock();
    lock.targets = ["claude", "codex"];
    const path = join(tmp.path, "targets.lock");
    writeLockfile(path, lock);
    assert.deepEqual(readLockfile(path)!.targets, ["claude", "codex"]);
    assert.ok(!serializeLockfile(sampleLock()).includes("targets:"));
  });

  it("defaults absent targets to claude", () => {
    const path = join(tmp.path, "pre-targets.lock");
    writeLockfile(path, sampleLock());
    assert.deepEqual(readLockfile(path)!.targets, ["claude"]);
  });

  it("reports a targets change as a problem", () => {
    const manifest = parseManifest(
      "targets: [claude, codex]\nskills:\n  remote: github:o/r/skills/remote@v1\n  local: ./skills/local\ncompose:\n  both:\n    use: [remote, local]",
      "t.yaml"
    );
    const problems = lockfileProblems(manifest, sampleLock());
    assert.deepEqual(problems, [
      "targets changed (manifest: claude, codex; lockfile: claude)",
    ]);
  });
});
