import { afterEach, describe, it } from "node:test";
import assert from "node:assert/strict";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

import { compile } from "./compiler.js";
import { loadConfig } from "./config.js";
import { resolveSkills } from "./resolver.js";

function makeTmpDir(): string {
  const dir = join(tmpdir(), `skillfold-watch-test-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  mkdirSync(dir, { recursive: true });
  return dir;
}

function writeSkill(dir: string, name: string, body: string): void {
  const skillDir = join(dir, "skills", name);
  mkdirSync(skillDir, { recursive: true });
  writeFileSync(join(skillDir, "SKILL.md"), body, "utf-8");
}

function writeConfig(dir: string, content: string): string {
  const configPath = join(dir, "skillfold.yaml");
  writeFileSync(configPath, content, "utf-8");
  return configPath;
}

describe("watch: compile cycle", () => {
  let tmpDir: string | undefined;

  afterEach(() => {
    if (tmpDir) {
      rmSync(tmpDir, { recursive: true, force: true });
      tmpDir = undefined;
    }
  });

  it("compiles on initial run and recompiles after skill change", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "build");

    writeSkill(tmpDir, "greeting", "Say hello.");
    const configPath = writeConfig(tmpDir, `name: watch-test
skills:
  atomic:
    greeting: ./skills/greeting
  composed:
    bot:
      compose: [greeting]
      description: "A bot."
`);

    // Initial compile
    const config = await loadConfig(configPath);
    const bodies = await resolveSkills(config, tmpDir);
    compile(config, bodies, outDir, "1.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "bot", "SKILL.md"), "utf-8");
    assert.ok(content.includes("Say hello."));
    assert.ok(content.includes("Generated by skillfold v1.0.0 from watch-test (skillfold.yaml)"));

    // Simulate skill change
    writeSkill(tmpDir, "greeting", "Say goodbye.");

    // Recompile (simulating what watch does)
    const config2 = await loadConfig(configPath);
    const bodies2 = await resolveSkills(config2, tmpDir);
    compile(config2, bodies2, outDir, "1.0.0", "skillfold.yaml");

    const content2 = readFileSync(join(outDir, "bot", "SKILL.md"), "utf-8");
    assert.ok(content2.includes("Say goodbye."));
    assert.ok(!content2.includes("Say hello."));
  });

  it("handles config error gracefully during recompile", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "build");

    writeSkill(tmpDir, "task", "Do the task.");
    const configPath = writeConfig(tmpDir, `name: error-test
skills:
  atomic:
    task: ./skills/task
  composed:
    worker:
      compose: [task]
      description: "A worker."
`);

    // Initial compile works
    const config = await loadConfig(configPath);
    const bodies = await resolveSkills(config, tmpDir);
    compile(config, bodies, outDir, "1.0.0", "skillfold.yaml");
    assert.ok(existsSync(join(outDir, "worker", "SKILL.md")));

    // Write invalid config
    writeConfig(tmpDir, "not: valid: yaml: [");

    // loadConfig should throw
    await assert.rejects(
      () => loadConfig(configPath),
      (err: unknown) => err instanceof Error
    );

    // Previous output still exists (watch would not have overwritten it)
    assert.ok(existsSync(join(outDir, "worker", "SKILL.md")));
  });

  it("picks up new skill directories after config change", async () => {
    tmpDir = makeTmpDir();
    const outDir = join(tmpDir, "build");

    writeSkill(tmpDir, "alpha", "Alpha body.");
    writeConfig(tmpDir, `name: dynamic-test
skills:
  atomic:
    alpha: ./skills/alpha
  composed:
    agent:
      compose: [alpha]
      description: "An agent."
`);

    const configPath = join(tmpDir, "skillfold.yaml");
    const config = await loadConfig(configPath);
    const bodies = await resolveSkills(config, tmpDir);
    compile(config, bodies, outDir, "1.0.0", "skillfold.yaml");

    const content = readFileSync(join(outDir, "agent", "SKILL.md"), "utf-8");
    assert.ok(content.includes("Alpha body."));

    // Add new skill and update config
    writeSkill(tmpDir, "beta", "Beta body.");
    writeConfig(tmpDir, `name: dynamic-test
skills:
  atomic:
    alpha: ./skills/alpha
    beta: ./skills/beta
  composed:
    agent:
      compose: [alpha, beta]
      description: "An agent."
`);

    // Recompile with new config
    const config2 = await loadConfig(configPath);
    const bodies2 = await resolveSkills(config2, tmpDir);
    compile(config2, bodies2, outDir, "1.0.0", "skillfold.yaml");

    const content2 = readFileSync(join(outDir, "agent", "SKILL.md"), "utf-8");
    assert.ok(content2.includes("Alpha body."));
    assert.ok(content2.includes("Beta body."));
  });
});
